CREATE TABLE `pi_integrity_alerts` (
  `Seq` bigint UNSIGNED NOT NULL DEFAULT (UUID_SHORT()),
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `alert_key` varchar(80) COLLATE utf8mb4_unicode_ci NOT NULL,
  `severity` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'warning',
  `message` varchar(240) COLLATE utf8mb4_unicode_ci NOT NULL,
  `details_json` text COLLATE utf8mb4_unicode_ci,
  `created_at` bigint UNSIGNED NOT NULL DEFAULT '0',
  `resolved_at` bigint UNSIGNED DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_integrity_alerts_seq` (`Seq`),
  KEY `idx_pi_integrity_alerts_key` (`alert_key`,`created_at`),
  KEY `idx_pi_integrity_alerts_open` (`resolved_at`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `pi_login_locks` (
  `Seq` bigint UNSIGNED NOT NULL DEFAULT (UUID_SHORT()),
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `subject_hash` char(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `ip_hash` char(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `fail_count` int UNSIGNED NOT NULL DEFAULT '0',
  `locked_until` bigint UNSIGNED DEFAULT NULL,
  `updated_at` bigint UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_login_subject_ip` (`subject_hash`,`ip_hash`),
  UNIQUE KEY `uq_login_locks_seq` (`Seq`),
  KEY `idx_login_locked` (`locked_until`),
  KEY `idx_login_subject_recent` (`subject_hash`,`locked_until`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `pi_maestro_job_runs` (
  `Seq` bigint UNSIGNED NOT NULL DEFAULT (UUID_SHORT()),
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `started_at` bigint UNSIGNED NOT NULL DEFAULT '0',
  `finished_at` bigint UNSIGNED DEFAULT NULL,
  `duration_ms` int UNSIGNED NOT NULL DEFAULT '0',
  `rules_seen` int UNSIGNED NOT NULL DEFAULT '0',
  `rules_run` int UNSIGNED NOT NULL DEFAULT '0',
  `actions_created` int UNSIGNED NOT NULL DEFAULT '0',
  `deferred_count` int UNSIGNED NOT NULL DEFAULT '0',
  `errors_count` int UNSIGNED NOT NULL DEFAULT '0',
  `success` tinyint(1) NOT NULL DEFAULT '1',
  `load_score` decimal(6,3) NOT NULL DEFAULT '0.000',
  `note` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_maestro_job_runs_seq` (`Seq`),
  KEY `idx_maestro_job_started` (`started_at`,`id`),
  KEY `idx_maestro_job_success` (`success`,`finished_at`,`id`),
  KEY `idx_maestro_job_recent` (`finished_at`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `pi_maestro_job_stats` (
  `Seq` bigint UNSIGNED NOT NULL DEFAULT (UUID_SHORT()),
  `routine_key` varchar(120) COLLATE utf8mb4_unicode_ci NOT NULL,
  `ewma_duration_ms` decimal(10,3) NOT NULL DEFAULT '0.000',
  `ewma_yield` decimal(10,3) NOT NULL DEFAULT '0.000',
  `run_count` int UNSIGNED NOT NULL DEFAULT '0',
  `skip_count` int UNSIGNED NOT NULL DEFAULT '0',
  `last_score` decimal(10,3) NOT NULL DEFAULT '0.000',
  `last_run_at` bigint UNSIGNED DEFAULT NULL,
  `updated_at` bigint UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`routine_key`),
  UNIQUE KEY `uq_maestro_job_stats_seq` (`Seq`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `pi_meta` (
  `Seq` bigint UNSIGNED NOT NULL DEFAULT (UUID_SHORT()),
  `meta_key` varchar(80) COLLATE utf8mb4_unicode_ci NOT NULL,
  `meta_value` text COLLATE utf8mb4_unicode_ci,
  `updated_at` bigint UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`meta_key`),
  UNIQUE KEY `uq_meta_seq` (`Seq`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `pi_persons` (
  `Seq` bigint UNSIGNED NOT NULL DEFAULT (UUID_SHORT()),
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `full_name` varchar(180) COLLATE utf8mb4_unicode_ci NOT NULL,
  `cpf` char(11) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `birth_date` bigint UNSIGNED DEFAULT NULL,
  `legal_type` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `legal_document` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `phone` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `email` varchar(180) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `address_zip` char(8) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `address` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `address_number` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `address_neighborhood` varchar(120) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `address_complement` varchar(120) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `address_state` char(2) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `address_city` varchar(120) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `address_city_ibge` int UNSIGNED DEFAULT NULL,
  `assinatura` char(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `clinic_id` int UNSIGNED DEFAULT NULL,
  `created_at` bigint UNSIGNED NOT NULL DEFAULT '0',
  `updated_at` bigint UNSIGNED DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `cpf` (`cpf`),
  UNIQUE KEY `uq_persons_seq` (`Seq`),
  UNIQUE KEY `uq_persons_clinic_id` (`clinic_id`,`id`),
  KEY `idx_persons_name` (`full_name`),
  KEY `idx_persons_doc` (`legal_document`),
  KEY `idx_persons_phone` (`phone`),
  KEY `idx_persons_email` (`email`),
  KEY `idx_persons_geo` (`address_state`,`address_city`),
  KEY `idx_persons_assinatura` (`assinatura`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `pi_platform_counters` (
  `Seq` bigint UNSIGNED NOT NULL DEFAULT (UUID_SHORT()),
  `counter_key` varchar(120) COLLATE utf8mb4_unicode_ci NOT NULL,
  `counter_value` bigint NOT NULL DEFAULT '0',
  `updated_at` bigint UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`counter_key`),
  UNIQUE KEY `uq_platform_counters_seq` (`Seq`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `pi_users` (
  `Seq` bigint UNSIGNED NOT NULL DEFAULT (UUID_SHORT()),
  `id` int UNSIGNED NOT NULL AUTO_INCREMENT,
  `person_id` bigint UNSIGNED NOT NULL,
  `name` varchar(180) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(180) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `password_hash` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `is_global_admin` tinyint(1) NOT NULL DEFAULT '0',
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `failed_login_count` smallint UNSIGNED NOT NULL DEFAULT '0',
  `locked_until` bigint UNSIGNED DEFAULT NULL,
  `last_login_at` bigint UNSIGNED DEFAULT NULL,
  `created_at` bigint UNSIGNED NOT NULL DEFAULT '0',
  `updated_at` bigint UNSIGNED DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `email` (`email`),
  UNIQUE KEY `uq_users_seq` (`Seq`),
  KEY `idx_users_active` (`active`,`name`),
  KEY `idx_users_global` (`is_global_admin`,`active`),
  KEY `idx_users_person` (`person_id`),
  CONSTRAINT `fk_users_person` FOREIGN KEY (`person_id`) REFERENCES `pi_persons` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `pi_clinics` (
  `Seq` bigint UNSIGNED NOT NULL DEFAULT (UUID_SHORT()),
  `id` int UNSIGNED NOT NULL AUTO_INCREMENT,
  `legal_type` enum('cpf','cnpj') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'cpf',
  `legal_name` varchar(180) COLLATE utf8mb4_unicode_ci NOT NULL,
  `legal_document` varchar(18) COLLATE utf8mb4_unicode_ci NOT NULL,
  `display_name` varchar(120) COLLATE utf8mb4_unicode_ci NOT NULL,
  `phone` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `responsible_profession` varchar(80) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'Médico(a)',
  `clinic_icon` varchar(60) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'medical_services',
  `accent_color` char(7) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '#334155',
  `owner_user_id` int UNSIGNED NOT NULL,
  `manager_user_id` int UNSIGNED NOT NULL,
  `address_line` varchar(180) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `address_state` char(2) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `address_city` varchar(120) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `address_city_ibge` int UNSIGNED DEFAULT NULL,
  `timezone` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'America/Cuiaba',
  `workflow_note` text COLLATE utf8mb4_unicode_ci,
  `onboarding_done` tinyint(1) NOT NULL DEFAULT '0',
  `onboarding_completed_at` bigint UNSIGNED DEFAULT NULL,
  `trial_started_at` bigint UNSIGNED DEFAULT NULL,
  `trial_ends_at` bigint UNSIGNED DEFAULT NULL,
  `subscription_status` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'trial',
  `paid_until` bigint UNSIGNED DEFAULT NULL,
  `monthly_price_cents` int UNSIGNED NOT NULL DEFAULT '9990',
  `document_code_alphabet` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `document_sequence` int UNSIGNED NOT NULL DEFAULT '0',
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `deleted_at` bigint UNSIGNED DEFAULT NULL,
  `deleted_by` int UNSIGNED DEFAULT NULL,
  `last_actor_signature` char(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `record_hash` char(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` bigint UNSIGNED NOT NULL DEFAULT '0',
  `updated_at` bigint UNSIGNED DEFAULT NULL,
  `subscription_trust_blocked_until` bigint UNSIGNED DEFAULT NULL,
  `subscription_last_payment_claim_at` bigint UNSIGNED DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_clinic_doc` (`legal_document`),
  UNIQUE KEY `uq_clinics_seq` (`Seq`),
  KEY `idx_clinic_active` (`active`,`display_name`),
  KEY `idx_clinic_owner` (`owner_user_id`),
  KEY `idx_clinic_manager` (`manager_user_id`),
  KEY `idx_clinic_geo` (`address_state`,`address_city`),
  KEY `idx_clinic_tz` (`timezone`),
  KEY `idx_clinic_subscription_due` (`active`,`subscription_status`,`paid_until`,`trial_ends_at`,`id`),
  KEY `idx_fk_clinics_deleted_by` (`deleted_by`),
  CONSTRAINT `fk_clinics_deleted_by` FOREIGN KEY (`deleted_by`) REFERENCES `pi_users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_clinics_manager_user` FOREIGN KEY (`manager_user_id`) REFERENCES `pi_users` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_clinics_owner_user` FOREIGN KEY (`owner_user_id`) REFERENCES `pi_users` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `pi_global_notices` (
  `Seq` bigint UNSIGNED NOT NULL DEFAULT (UUID_SHORT()),
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` varchar(180) COLLATE utf8mb4_unicode_ci NOT NULL,
  `body` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `severity` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'info',
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `starts_at` bigint UNSIGNED DEFAULT NULL,
  `expires_at` bigint UNSIGNED DEFAULT NULL,
  `created_by` int UNSIGNED DEFAULT NULL,
  `created_at` bigint UNSIGNED NOT NULL DEFAULT '0',
  `updated_at` bigint UNSIGNED DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_global_notices_seq` (`Seq`),
  KEY `idx_global_notices_active` (`active`,`starts_at`,`expires_at`,`created_at`),
  KEY `idx_fk_global_notices_created_by` (`created_by`),
  CONSTRAINT `fk_global_notices_created_by` FOREIGN KEY (`created_by`) REFERENCES `pi_users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `pi_user_cmdbar_access` (
  `Seq` bigint UNSIGNED NOT NULL DEFAULT (UUID_SHORT()),
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` int UNSIGNED NOT NULL,
  `scope` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'clinic',
  `clinic_scope_id` int UNSIGNED NOT NULL DEFAULT '0',
  `role_code` varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `action_key` varchar(80) COLLATE utf8mb4_unicode_ci NOT NULL,
  `last_accessed_at` bigint UNSIGNED NOT NULL DEFAULT '0',
  `access_count` int UNSIGNED NOT NULL DEFAULT '1',
  `created_at` bigint UNSIGNED NOT NULL DEFAULT '0',
  `updated_at` bigint UNSIGNED DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_user_cmdbar_context` (`user_id`,`scope`,`clinic_scope_id`,`role_code`,`action_key`),
  UNIQUE KEY `uq_user_cmdbar_access_seq` (`Seq`),
  KEY `idx_user_cmdbar_recent` (`user_id`,`scope`,`clinic_scope_id`,`role_code`,`last_accessed_at`),
  KEY `idx_user_cmdbar_action` (`action_key`,`last_accessed_at`),
  CONSTRAINT `fk_user_cmdbar_access_user` FOREIGN KEY (`user_id`) REFERENCES `pi_users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `pi_user_onboarding_tips` (
  `Seq` bigint UNSIGNED NOT NULL DEFAULT (UUID_SHORT()),
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` int UNSIGNED NOT NULL,
  `tip_key` varchar(120) COLLATE utf8mb4_unicode_ci NOT NULL,
  `dismissed_at` bigint UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_user_tip` (`user_id`,`tip_key`),
  UNIQUE KEY `uq_user_onboarding_tips_seq` (`Seq`),
  KEY `idx_user_onboarding_tips_user` (`user_id`,`dismissed_at`),
  CONSTRAINT `fk_user_onboarding_tips_user` FOREIGN KEY (`user_id`) REFERENCES `pi_users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `pi_action_ledger` (
  `Seq` bigint UNSIGNED NOT NULL DEFAULT (UUID_SHORT()),
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `request_id` char(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `clinic_id` int UNSIGNED DEFAULT NULL,
  `user_id` int UNSIGNED DEFAULT NULL,
  `route` varchar(80) COLLATE utf8mb4_unicode_ci NOT NULL,
  `action_key` varchar(80) COLLATE utf8mb4_unicode_ci NOT NULL,
  `module_key` varchar(80) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `operation_key` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `scope` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `role_code` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `allowed` tinyint(1) NOT NULL DEFAULT '0',
  `status` varchar(24) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'authorized',
  `reason` varchar(180) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `authorization_hash` char(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `contract_hash` char(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `mutation_hash` char(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `mutation_count` smallint UNSIGNED NOT NULL DEFAULT '0',
  `affected_tables_json` json DEFAULT NULL,
  `mutation_json` json DEFAULT NULL,
  `context_json` json DEFAULT NULL,
  `policy_version` varchar(60) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` bigint UNSIGNED NOT NULL DEFAULT '0',
  `finalized_at` bigint UNSIGNED DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_action_ledger_seq` (`Seq`),
  UNIQUE KEY `uq_action_ledger_authorization` (`authorization_hash`),
  UNIQUE KEY `uq_action_ledger_clinic_id` (`clinic_id`,`id`),
  KEY `idx_action_ledger_request` (`request_id`,`id`),
  KEY `idx_action_ledger_scope` (`clinic_id`,`created_at`,`id`),
  KEY `idx_action_ledger_user` (`user_id`,`created_at`,`id`),
  KEY `idx_action_ledger_status` (`status`,`created_at`,`id`),
  KEY `idx_action_ledger_policy` (`policy_version`,`created_at`,`id`),
  CONSTRAINT `fk_action_ledger_clinic` FOREIGN KEY (`clinic_id`) REFERENCES `pi_clinics` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_action_ledger_user` FOREIGN KEY (`user_id`) REFERENCES `pi_users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `pi_admin_alerts` (
  `Seq` bigint UNSIGNED NOT NULL DEFAULT (UUID_SHORT()),
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `sender_user_id` int UNSIGNED NOT NULL,
  `sender_clinic_id` int UNSIGNED DEFAULT NULL,
  `source_scope` varchar(24) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'admin',
  `recipient_user_id` int UNSIGNED DEFAULT NULL,
  `title` varchar(180) COLLATE utf8mb4_unicode_ci NOT NULL,
  `body` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `severity` varchar(24) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'info',
  `read_at` bigint UNSIGNED DEFAULT NULL,
  `read_by` int UNSIGNED DEFAULT NULL,
  `created_at` bigint UNSIGNED NOT NULL DEFAULT '0',
  `updated_at` bigint UNSIGNED DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_admin_alerts_seq` (`Seq`),
  KEY `idx_admin_alerts_recipient` (`recipient_user_id`,`created_at`,`id`),
  KEY `idx_admin_alerts_sender` (`sender_user_id`,`created_at`,`id`),
  KEY `idx_admin_alerts_clinic` (`sender_clinic_id`,`created_at`,`id`),
  KEY `idx_admin_alerts_severity` (`severity`,`created_at`,`id`),
  KEY `idx_fk_admin_alerts_read_by` (`read_by`),
  CONSTRAINT `fk_admin_alerts_clinic` FOREIGN KEY (`sender_clinic_id`) REFERENCES `pi_clinics` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_admin_alerts_read_by` FOREIGN KEY (`read_by`) REFERENCES `pi_users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_admin_alerts_recipient` FOREIGN KEY (`recipient_user_id`) REFERENCES `pi_users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_admin_alerts_sender` FOREIGN KEY (`sender_user_id`) REFERENCES `pi_users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `pi_agenda_notes` (
  `Seq` bigint UNSIGNED NOT NULL DEFAULT (UUID_SHORT()),
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `clinic_id` int UNSIGNED NOT NULL,
  `doctor_user_id` int UNSIGNED DEFAULT NULL,
  `note_date` bigint UNSIGNED NOT NULL DEFAULT '0',
  `start_at` bigint UNSIGNED DEFAULT NULL,
  `end_at` bigint UNSIGNED DEFAULT NULL,
  `content` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `target_scope` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'clinic',
  `target_role` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_by` int UNSIGNED DEFAULT NULL,
  `updated_by` int UNSIGNED DEFAULT NULL,
  `deleted_by` int UNSIGNED DEFAULT NULL,
  `created_at` bigint UNSIGNED NOT NULL DEFAULT '0',
  `updated_at` bigint UNSIGNED DEFAULT NULL,
  `deleted_at` bigint UNSIGNED DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_agenda_notes_clinic_id` (`clinic_id`,`id`),
  UNIQUE KEY `uq_agenda_notes_seq` (`Seq`),
  KEY `idx_agenda_notes_day_visible` (`clinic_id`,`note_date`,`target_scope`,`target_role`,`deleted_at`,`id`),
  KEY `idx_agenda_notes_timed` (`clinic_id`,`doctor_user_id`,`note_date`,`start_at`,`end_at`,`deleted_at`,`id`),
  KEY `idx_agenda_notes_created` (`clinic_id`,`created_at`,`id`),
  KEY `idx_agenda_notes_deleted` (`clinic_id`,`deleted_at`,`id`),
  KEY `idx_fk_agenda_notes_doctor_user_id` (`doctor_user_id`),
  KEY `idx_fk_agenda_notes_created_by` (`created_by`),
  KEY `idx_fk_agenda_notes_updated_by` (`updated_by`),
  KEY `idx_fk_agenda_notes_deleted_by` (`deleted_by`),
  CONSTRAINT `fk_agenda_notes_clinic` FOREIGN KEY (`clinic_id`) REFERENCES `pi_clinics` (`id`),
  CONSTRAINT `fk_agenda_notes_doctor_user` FOREIGN KEY (`doctor_user_id`) REFERENCES `pi_users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_agenda_notes_created_by` FOREIGN KEY (`created_by`) REFERENCES `pi_users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_agenda_notes_deleted_by` FOREIGN KEY (`deleted_by`) REFERENCES `pi_users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_agenda_notes_updated_by` FOREIGN KEY (`updated_by`) REFERENCES `pi_users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `pi_audit` (
  `Seq` bigint UNSIGNED NOT NULL DEFAULT (UUID_SHORT()),
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `clinic_id` int UNSIGNED DEFAULT NULL,
  `user_id` int UNSIGNED DEFAULT NULL,
  `event_key` varchar(80) COLLATE utf8mb4_unicode_ci NOT NULL,
  `event_label` varchar(120) COLLATE utf8mb4_unicode_ci NOT NULL,
  `event_icon` varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'radio_button_checked',
  `entity_key` varchar(60) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `entity_label` varchar(80) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `entity_id` varchar(80) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `friendly_text` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `context_json` json DEFAULT NULL,
  `integrity_hash` char(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `previous_hash` char(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `chain_hash` char(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `proof_hash` char(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `proof_json` json DEFAULT NULL,
  `policy_version` varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'audit-chain-v1',
  `actor_signature` char(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ip_hash` char(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `user_agent` varchar(180) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` bigint UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_audit_seq` (`Seq`),
  UNIQUE KEY `uq_audit_clinic_id` (`clinic_id`,`id`),
  KEY `idx_audit_user` (`clinic_id`,`user_id`,`created_at`,`id`),
  KEY `idx_audit_global` (`created_at`,`id`),
  KEY `idx_audit_event` (`event_key`,`created_at`,`id`),
  KEY `idx_audit_entity` (`entity_key`,`entity_id`,`created_at`,`id`),
  KEY `idx_audit_chain_hash` (`chain_hash`),
  KEY `idx_audit_policy_created` (`policy_version`,`created_at`,`id`),
  KEY `idx_audit_integrity_recent` (`created_at`,`integrity_hash`),
  KEY `idx_audit_clinic_created_id` (`clinic_id`,`created_at`,`id`),
  KEY `idx_audit_user_created_id` (`user_id`,`created_at`,`id`),
  CONSTRAINT `fk_audit_clinic` FOREIGN KEY (`clinic_id`) REFERENCES `pi_clinics` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_audit_user` FOREIGN KEY (`user_id`) REFERENCES `pi_users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `pi_blocks` (
  `Seq` bigint UNSIGNED NOT NULL DEFAULT (UUID_SHORT()),
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `clinic_id` int UNSIGNED NOT NULL,
  `doctor_user_id` int UNSIGNED DEFAULT NULL,
  `start_at` bigint UNSIGNED NOT NULL DEFAULT '0',
  `end_at` bigint UNSIGNED NOT NULL DEFAULT '0',
  `reason` varchar(180) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_by` int UNSIGNED DEFAULT NULL,
  `deleted_at` bigint UNSIGNED DEFAULT NULL,
  `deleted_by` int UNSIGNED DEFAULT NULL,
  `cancel_reason` varchar(180) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `updated_at` bigint UNSIGNED DEFAULT NULL,
  `created_at` bigint UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_blocks_clinic_id` (`clinic_id`,`id`),
  UNIQUE KEY `uq_blocks_seq` (`Seq`),
  KEY `idx_blocks_day` (`clinic_id`,`start_at`,`end_at`),
  KEY `idx_blocks_doctor` (`clinic_id`,`doctor_user_id`,`start_at`),
  KEY `idx_fk_blocks_doctor_user_id` (`doctor_user_id`),
  KEY `idx_fk_blocks_created_by` (`created_by`),
  KEY `idx_fk_blocks_deleted_by` (`deleted_by`),
  CONSTRAINT `fk_blocks_clinic` FOREIGN KEY (`clinic_id`) REFERENCES `pi_clinics` (`id`),
  CONSTRAINT `fk_blocks_created_by` FOREIGN KEY (`created_by`) REFERENCES `pi_users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_blocks_deleted_by` FOREIGN KEY (`deleted_by`) REFERENCES `pi_users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_blocks_doctor` FOREIGN KEY (`doctor_user_id`) REFERENCES `pi_users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `pi_clinic_daily_stats` (
  `Seq` bigint UNSIGNED NOT NULL DEFAULT (UUID_SHORT()),
  `clinic_id` int UNSIGNED NOT NULL,
  `day_date` bigint UNSIGNED NOT NULL DEFAULT '0',
  `metric_key` varchar(80) COLLATE utf8mb4_unicode_ci NOT NULL,
  `metric_value` bigint NOT NULL DEFAULT '0',
  `updated_at` bigint UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`clinic_id`,`day_date`,`metric_key`),
  UNIQUE KEY `uq_clinic_daily_stats_seq` (`Seq`),
  KEY `idx_daily_metric` (`day_date`,`metric_key`),
  CONSTRAINT `fk_clinic_daily_stats_clinic` FOREIGN KEY (`clinic_id`) REFERENCES `pi_clinics` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `pi_clinic_roles` (
  `Seq` bigint UNSIGNED NOT NULL DEFAULT (UUID_SHORT()),
  `clinic_id` int UNSIGNED NOT NULL,
  `role_code` varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL,
  `label` varchar(80) COLLATE utf8mb4_unicode_ci NOT NULL,
  `enabled` tinyint(1) NOT NULL DEFAULT '1',
  `sort_order` tinyint UNSIGNED NOT NULL DEFAULT '10',
  `updated_at` bigint UNSIGNED NOT NULL DEFAULT '0',
  `icon_name` varchar(60) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'support_agent',
  PRIMARY KEY (`clinic_id`,`role_code`),
  UNIQUE KEY `uq_clinic_roles_seq` (`Seq`),
  KEY `idx_cr_enabled` (`clinic_id`,`enabled`,`sort_order`),
  CONSTRAINT `fk_cr_clinic` FOREIGN KEY (`clinic_id`) REFERENCES `pi_clinics` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `pi_document_templates` (
  `Seq` bigint UNSIGNED NOT NULL DEFAULT (UUID_SHORT()),
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `clinic_id` int UNSIGNED NOT NULL,
  `owner_user_id` int UNSIGNED NOT NULL,
  `owner_role` varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL,
  `type_key` varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'declaracao',
  `title` varchar(160) COLLATE utf8mb4_unicode_ci NOT NULL,
  `body` mediumtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `status` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'approved',
  `approval_required` tinyint(1) NOT NULL DEFAULT '0',
  `approved_by` int UNSIGNED DEFAULT NULL,
  `approved_at` bigint UNSIGNED DEFAULT NULL,
  `updated_by` int UNSIGNED DEFAULT NULL,
  `created_at` bigint UNSIGNED NOT NULL DEFAULT '0',
  `updated_at` bigint UNSIGNED DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_document_templates_clinic_id` (`clinic_id`,`id`),
  UNIQUE KEY `uq_document_templates_seq` (`Seq`),
  KEY `idx_doc_tpl_scope` (`clinic_id`,`owner_user_id`,`status`),
  KEY `idx_doc_tpl_type` (`clinic_id`,`type_key`,`status`),
  KEY `idx_doc_tpl_pending` (`clinic_id`,`status`,`approval_required`),
  KEY `idx_doc_tpl_role_status` (`clinic_id`,`owner_role`,`status`,`updated_at`,`id`),
  KEY `idx_fk_document_templates_owner_user_id` (`owner_user_id`),
  KEY `idx_fk_document_templates_approved_by` (`approved_by`),
  KEY `idx_fk_document_templates_updated_by` (`updated_by`),
  CONSTRAINT `fk_doc_tpl_approved_by` FOREIGN KEY (`approved_by`) REFERENCES `pi_users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_doc_tpl_owner` FOREIGN KEY (`owner_user_id`) REFERENCES `pi_users` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_doc_tpl_updated_by` FOREIGN KEY (`updated_by`) REFERENCES `pi_users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_document_templates_clinic` FOREIGN KEY (`clinic_id`) REFERENCES `pi_clinics` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `pi_error_events` (
  `Seq` bigint UNSIGNED NOT NULL DEFAULT (UUID_SHORT()),
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `route` varchar(80) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `method` varchar(12) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `http_status` smallint UNSIGNED DEFAULT NULL,
  `message` varchar(900) COLLATE utf8mb4_unicode_ci NOT NULL,
  `file` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `line` int UNSIGNED DEFAULT NULL,
  `user_id` int UNSIGNED DEFAULT NULL,
  `clinic_id` int UNSIGNED DEFAULT NULL,
  `notes` text COLLATE utf8mb4_unicode_ci,
  `resolved_at` bigint UNSIGNED DEFAULT NULL,
  `created_at` bigint UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_error_events_seq` (`Seq`),
  UNIQUE KEY `uq_error_events_clinic_id` (`clinic_id`,`id`),
  KEY `idx_errors_route` (`route`,`created_at`),
  KEY `idx_errors_created` (`created_at`,`id`),
  KEY `idx_error_events_resolved_created` (`resolved_at`,`created_at`,`id`),
  KEY `idx_fk_error_events_user_id` (`user_id`),
  CONSTRAINT `fk_error_events_clinic` FOREIGN KEY (`clinic_id`) REFERENCES `pi_clinics` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_error_events_user` FOREIGN KEY (`user_id`) REFERENCES `pi_users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `pi_financial_accounts` (
  `Seq` bigint UNSIGNED NOT NULL DEFAULT (UUID_SHORT()),
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `clinic_id` int UNSIGNED NOT NULL,
  `name` varchar(120) COLLATE utf8mb4_unicode_ci NOT NULL,
  `bank_name` varchar(120) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `bank_code` varchar(5) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `branch_number` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `account_number` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `account_digit` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `account_type` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pix_key` varchar(160) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `opening_balance_cents` int NOT NULL DEFAULT '0',
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `created_by` int UNSIGNED DEFAULT NULL,
  `created_at` bigint UNSIGNED NOT NULL DEFAULT '0',
  `updated_at` bigint UNSIGNED DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_financial_accounts_clinic_id` (`clinic_id`,`id`),
  UNIQUE KEY `uq_financial_accounts_seq` (`Seq`),
  KEY `idx_fin_accounts` (`clinic_id`,`active`,`name`),
  KEY `idx_fk_financial_accounts_created_by` (`created_by`),
  CONSTRAINT `fk_fin_accounts_clinic` FOREIGN KEY (`clinic_id`) REFERENCES `pi_clinics` (`id`),
  CONSTRAINT `fk_fin_accounts_created_by` FOREIGN KEY (`created_by`) REFERENCES `pi_users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `pi_financial_counterparties` (
  `Seq` bigint UNSIGNED NOT NULL DEFAULT (UUID_SHORT()),
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `clinic_id` int UNSIGNED NOT NULL,
  `person_id` bigint UNSIGNED NOT NULL,
  `kind` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'credor',
  `notes` text COLLATE utf8mb4_unicode_ci,
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `created_by` int UNSIGNED DEFAULT NULL,
  `created_at` bigint UNSIGNED NOT NULL DEFAULT '0',
  `updated_at` bigint UNSIGNED DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_fin_counterparty` (`clinic_id`,`person_id`,`kind`),
  UNIQUE KEY `uq_financial_counterparties_clinic_id` (`clinic_id`,`id`),
  UNIQUE KEY `uq_financial_counterparties_seq` (`Seq`),
  KEY `idx_fin_counterparties` (`clinic_id`,`kind`,`active`),
  KEY `idx_fk_financial_counterparties_person_id` (`person_id`),
  KEY `idx_fk_financial_counterparties_created_by` (`created_by`),
  CONSTRAINT `fk_fin_counterparties_created_by` FOREIGN KEY (`created_by`) REFERENCES `pi_users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_fin_counterparty_clinic` FOREIGN KEY (`clinic_id`) REFERENCES `pi_clinics` (`id`),
  CONSTRAINT `fk_fin_counterparty_person` FOREIGN KEY (`person_id`) REFERENCES `pi_persons` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `pi_financial_daily_closings` (
  `Seq` bigint UNSIGNED NOT NULL DEFAULT (UUID_SHORT()),
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `clinic_id` int UNSIGNED NOT NULL,
  `business_date` bigint UNSIGNED NOT NULL DEFAULT '0',
  `status` varchar(24) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'consolidado',
  `expected_cents` int NOT NULL DEFAULT '0',
  `received_cents` int NOT NULL DEFAULT '0',
  `pending_cents` int NOT NULL DEFAULT '0',
  `drawer_cents` int NOT NULL DEFAULT '0',
  `safe_cents` int NOT NULL DEFAULT '0',
  `bank_cents` int NOT NULL DEFAULT '0',
  `movement_count` int UNSIGNED NOT NULL DEFAULT '0',
  `closed_drawer_count` int UNSIGNED NOT NULL DEFAULT '0',
  `notes` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `consolidated_by` int UNSIGNED DEFAULT NULL,
  `consolidated_at` bigint UNSIGNED NOT NULL DEFAULT '0',
  `reopened_by` int UNSIGNED DEFAULT NULL,
  `reopened_at` bigint UNSIGNED DEFAULT NULL,
  `created_at` bigint UNSIGNED NOT NULL DEFAULT '0',
  `updated_at` bigint UNSIGNED DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_fin_daily_closing` (`clinic_id`,`business_date`),
  UNIQUE KEY `uq_financial_daily_closings_clinic_id` (`clinic_id`,`id`),
  UNIQUE KEY `uq_financial_daily_closings_seq` (`Seq`),
  KEY `idx_fin_daily_closing_status` (`clinic_id`,`status`,`business_date`),
  KEY `idx_fk_financial_daily_closings_consolidated_by` (`consolidated_by`),
  KEY `idx_fk_financial_daily_closings_reopened_by` (`reopened_by`),
  CONSTRAINT `fk_fin_daily_closing_clinic` FOREIGN KEY (`clinic_id`) REFERENCES `pi_clinics` (`id`),
  CONSTRAINT `fk_fin_daily_consolidated_by` FOREIGN KEY (`consolidated_by`) REFERENCES `pi_users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_fin_daily_reopened_by` FOREIGN KEY (`reopened_by`) REFERENCES `pi_users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `pi_financial_goals` (
  `Seq` bigint UNSIGNED NOT NULL DEFAULT (UUID_SHORT()),
  `clinic_id` int UNSIGNED NOT NULL,
  `month_key` char(7) COLLATE utf8mb4_unicode_ci NOT NULL,
  `target_cents` int UNSIGNED NOT NULL DEFAULT '0',
  `base_metric` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'efetivada',
  `share_with_team` tinyint(1) NOT NULL DEFAULT '0',
  `updated_by` int UNSIGNED DEFAULT NULL,
  `updated_at` bigint UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`clinic_id`,`month_key`),
  UNIQUE KEY `uq_financial_goals_seq` (`Seq`),
  KEY `idx_fin_goal_share` (`clinic_id`,`share_with_team`,`month_key`),
  KEY `idx_fk_financial_goals_updated_by` (`updated_by`),
  CONSTRAINT `fk_fin_goal_clinic` FOREIGN KEY (`clinic_id`) REFERENCES `pi_clinics` (`id`),
  CONSTRAINT `fk_fin_goals_updated_by` FOREIGN KEY (`updated_by`) REFERENCES `pi_users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `pi_financial_payment_methods` (
  `Seq` bigint UNSIGNED NOT NULL DEFAULT (UUID_SHORT()),
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `clinic_id` int UNSIGNED NOT NULL,
  `name` varchar(80) COLLATE utf8mb4_unicode_ci NOT NULL,
  `method_type` varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'outro',
  `settlement_days` smallint UNSIGNED NOT NULL DEFAULT '0',
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `created_by` int UNSIGNED DEFAULT NULL,
  `created_at` bigint UNSIGNED NOT NULL DEFAULT '0',
  `updated_at` bigint UNSIGNED DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_fin_payment_method` (`clinic_id`,`method_type`,`name`),
  UNIQUE KEY `uq_financial_payment_methods_clinic_id` (`clinic_id`,`id`),
  UNIQUE KEY `uq_financial_payment_methods_seq` (`Seq`),
  KEY `idx_fin_payment_methods` (`clinic_id`,`active`,`method_type`,`name`),
  KEY `idx_fk_financial_payment_methods_created_by` (`created_by`),
  CONSTRAINT `fk_fin_methods_created_by` FOREIGN KEY (`created_by`) REFERENCES `pi_users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_fin_pay_methods_clinic` FOREIGN KEY (`clinic_id`) REFERENCES `pi_clinics` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `pi_leads` (
  `Seq` bigint UNSIGNED NOT NULL DEFAULT (UUID_SHORT()),
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `clinic_id` int UNSIGNED NOT NULL,
  `person_id` bigint UNSIGNED DEFAULT NULL,
  `name` varchar(180) COLLATE utf8mb4_unicode_ci NOT NULL,
  `phone` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `phone_digits` varchar(11) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `source` varchar(80) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `interest` varchar(180) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `stage` varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'em_aberto',
  `next_action_at` bigint UNSIGNED DEFAULT NULL,
  `notes` text COLLATE utf8mb4_unicode_ci,
  `created_by` int UNSIGNED DEFAULT NULL,
  `created_at` bigint UNSIGNED NOT NULL DEFAULT '0',
  `updated_at` bigint UNSIGNED DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_leads_clinic_id` (`clinic_id`,`id`),
  UNIQUE KEY `uq_leads_seq` (`Seq`),
  KEY `idx_leads_scope` (`clinic_id`,`stage`,`next_action_at`),
  KEY `idx_leads_created` (`clinic_id`,`created_at`),
  KEY `idx_leads_phone` (`clinic_id`,`phone_digits`),
  KEY `idx_leads_person` (`person_id`),
  KEY `idx_fk_leads_created_by` (`created_by`),
  CONSTRAINT `fk_leads_clinic` FOREIGN KEY (`clinic_id`) REFERENCES `pi_clinics` (`id`),
  CONSTRAINT `fk_leads_created_by` FOREIGN KEY (`created_by`) REFERENCES `pi_users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `pi_maestro_rules` (
  `Seq` bigint UNSIGNED NOT NULL DEFAULT (UUID_SHORT()),
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `clinic_id` int UNSIGNED NOT NULL,
  `name` varchar(160) COLLATE utf8mb4_unicode_ci NOT NULL,
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `trigger_module` varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL,
  `trigger_event` varchar(80) COLLATE utf8mb4_unicode_ci NOT NULL,
  `condition_json` json DEFAULT NULL,
  `action_type` varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'create_task',
  `action_json` json DEFAULT NULL,
  `priority` tinyint UNSIGNED NOT NULL DEFAULT '50',
  `min_interval_minutes` smallint UNSIGNED NOT NULL DEFAULT '15',
  `last_run_at` bigint UNSIGNED DEFAULT NULL,
  `next_run_at` bigint UNSIGNED DEFAULT NULL,
  `run_count` int UNSIGNED NOT NULL DEFAULT '0',
  `created_by` int UNSIGNED DEFAULT NULL,
  `updated_by` int UNSIGNED DEFAULT NULL,
  `created_at` bigint UNSIGNED NOT NULL DEFAULT '0',
  `updated_at` bigint UNSIGNED DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_maestro_rules_clinic_id` (`clinic_id`,`id`),
  UNIQUE KEY `uq_maestro_rules_seq` (`Seq`),
  KEY `idx_maestro_due` (`clinic_id`,`active`,`next_run_at`,`priority`,`id`),
  KEY `idx_maestro_trigger` (`clinic_id`,`trigger_module`,`trigger_event`,`active`),
  KEY `idx_maestro_due_global` (`active`,`next_run_at`,`priority`,`id`),
  KEY `idx_fk_maestro_rules_created_by` (`created_by`),
  KEY `idx_fk_maestro_rules_updated_by` (`updated_by`),
  CONSTRAINT `fk_maestro_rules_clinic` FOREIGN KEY (`clinic_id`) REFERENCES `pi_clinics` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_maestro_rules_created_by` FOREIGN KEY (`created_by`) REFERENCES `pi_users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_maestro_rules_updated_by` FOREIGN KEY (`updated_by`) REFERENCES `pi_users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `pi_notices` (
  `Seq` bigint UNSIGNED NOT NULL DEFAULT (UUID_SHORT()),
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `clinic_id` int UNSIGNED NOT NULL,
  `title` varchar(180) COLLATE utf8mb4_unicode_ci NOT NULL,
  `body` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `requires_ack` tinyint(1) NOT NULL DEFAULT '1',
  `target_scope` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'all',
  `target_role` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `target_user_id` int UNSIGNED DEFAULT NULL,
  `created_by` int UNSIGNED DEFAULT NULL,
  `created_at` bigint UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_notices_clinic_id` (`clinic_id`,`id`),
  UNIQUE KEY `uq_notices_seq` (`Seq`),
  KEY `idx_notices_target` (`clinic_id`,`target_scope`,`target_role`,`target_user_id`,`id`),
  KEY `idx_notices_target_created` (`clinic_id`,`target_scope`,`target_role`,`target_user_id`,`created_at`,`id`),
  KEY `idx_fk_notices_created_by` (`created_by`),
  KEY `idx_fk_notices_target_user_id` (`target_user_id`),
  CONSTRAINT `fk_notices_clinic` FOREIGN KEY (`clinic_id`) REFERENCES `pi_clinics` (`id`),
  CONSTRAINT `fk_notices_created_by` FOREIGN KEY (`created_by`) REFERENCES `pi_users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_notices_target_user` FOREIGN KEY (`target_user_id`) REFERENCES `pi_users` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `pi_patients` (
  `Seq` bigint UNSIGNED NOT NULL DEFAULT (UUID_SHORT()),
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `clinic_id` int UNSIGNED NOT NULL,
  `person_id` bigint UNSIGNED NOT NULL,
  `phone` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `email` varchar(180) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `address` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `address_zip` char(8) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `address_number` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `address_neighborhood` varchar(120) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `address_complement` varchar(120) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `address_state` char(2) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `address_city` varchar(120) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `address_city_ibge` int UNSIGNED DEFAULT NULL,
  `tags` varchar(180) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `notes` text COLLATE utf8mb4_unicode_ci,
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `registration_needs_update` tinyint(1) NOT NULL DEFAULT '0',
  `deleted_at` bigint UNSIGNED DEFAULT NULL,
  `deleted_by` int UNSIGNED DEFAULT NULL,
  `restored_at` bigint UNSIGNED DEFAULT NULL,
  `restored_by` int UNSIGNED DEFAULT NULL,
  `created_by` int UNSIGNED DEFAULT NULL,
  `created_at` bigint UNSIGNED NOT NULL DEFAULT '0',
  `updated_at` bigint UNSIGNED DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_cp_person` (`clinic_id`,`person_id`),
  UNIQUE KEY `uq_patients_clinic_id` (`clinic_id`,`id`),
  UNIQUE KEY `uq_patients_seq` (`Seq`),
  KEY `idx_pat_created` (`clinic_id`,`created_at`),
  KEY `idx_pat_recent` (`clinic_id`,`active`,`id`),
  KEY `idx_pat_geo` (`clinic_id`,`address_state`,`address_city`),
  KEY `idx_pat_clinic_active_created_id` (`clinic_id`,`active`,`created_at`,`id`),
  KEY `idx_fk_patients_person_id` (`person_id`),
  KEY `idx_fk_patients_created_by` (`created_by`),
  KEY `idx_fk_patients_deleted_by` (`deleted_by`),
  KEY `idx_fk_patients_restored_by` (`restored_by`),
  CONSTRAINT `fk_pat_clinic` FOREIGN KEY (`clinic_id`) REFERENCES `pi_clinics` (`id`),
  CONSTRAINT `fk_pat_created_by` FOREIGN KEY (`created_by`) REFERENCES `pi_users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_pat_deleted_by` FOREIGN KEY (`deleted_by`) REFERENCES `pi_users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_pat_person` FOREIGN KEY (`person_id`) REFERENCES `pi_persons` (`id`),
  CONSTRAINT `fk_pat_restored_by` FOREIGN KEY (`restored_by`) REFERENCES `pi_users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `pi_permission_rules` (
  `Seq` bigint UNSIGNED NOT NULL DEFAULT (UUID_SHORT()),
  `clinic_id` int UNSIGNED NOT NULL,
  `role_code` varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL,
  `action_key` varchar(80) COLLATE utf8mb4_unicode_ci NOT NULL,
  `operation_key` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `allowed` tinyint(1) NOT NULL DEFAULT '0',
  `updated_at` bigint UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`clinic_id`,`role_code`,`action_key`,`operation_key`),
  UNIQUE KEY `uq_permission_rules_seq` (`Seq`),
  KEY `idx_perm_rules_role` (`clinic_id`,`role_code`,`allowed`),
  KEY `idx_perm_rules_action` (`clinic_id`,`action_key`,`operation_key`,`allowed`),
  CONSTRAINT `fk_permission_rules_clinic` FOREIGN KEY (`clinic_id`) REFERENCES `pi_clinics` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `pi_permissions` (
  `Seq` bigint UNSIGNED NOT NULL DEFAULT (UUID_SHORT()),
  `clinic_id` int UNSIGNED NOT NULL,
  `role_code` varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL,
  `action_key` varchar(80) COLLATE utf8mb4_unicode_ci NOT NULL,
  `allowed` tinyint(1) NOT NULL DEFAULT '0',
  `updated_at` bigint UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`clinic_id`,`role_code`,`action_key`),
  UNIQUE KEY `uq_permissions_seq` (`Seq`),
  KEY `idx_cp_role` (`clinic_id`,`role_code`,`allowed`),
  KEY `idx_cp_action` (`action_key`,`allowed`),
  CONSTRAINT `fk_perm_clinic` FOREIGN KEY (`clinic_id`) REFERENCES `pi_clinics` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `pi_procedures` (
  `Seq` bigint UNSIGNED NOT NULL DEFAULT (UUID_SHORT()),
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `clinic_id` int UNSIGNED NOT NULL,
  `title` varchar(160) COLLATE utf8mb4_unicode_ci NOT NULL,
  `category` varchar(80) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `description` text COLLATE utf8mb4_unicode_ci,
  `duration_minutes` smallint UNSIGNED NOT NULL DEFAULT '30',
  `price_cents` int UNSIGNED NOT NULL DEFAULT '0',
  `payment_methods` varchar(180) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pre_instructions` text COLLATE utf8mb4_unicode_ci,
  `post_care` text COLLATE utf8mb4_unicode_ci,
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `created_by` int UNSIGNED DEFAULT NULL,
  `updated_by` int UNSIGNED DEFAULT NULL,
  `created_at` bigint UNSIGNED NOT NULL DEFAULT '0',
  `updated_at` bigint UNSIGNED DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_procedures_clinic_id` (`clinic_id`,`id`),
  UNIQUE KEY `uq_procedures_seq` (`Seq`),
  KEY `idx_proc_recent` (`clinic_id`,`active`,`id`),
  KEY `idx_proc_clinic_active_title` (`clinic_id`,`active`,`title`),
  KEY `idx_fk_procedures_created_by` (`created_by`),
  KEY `idx_fk_procedures_updated_by` (`updated_by`),
  CONSTRAINT `fk_proc_clinic` FOREIGN KEY (`clinic_id`) REFERENCES `pi_clinics` (`id`),
  CONSTRAINT `fk_proc_created_by` FOREIGN KEY (`created_by`) REFERENCES `pi_users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_procedures_updated_by` FOREIGN KEY (`updated_by`) REFERENCES `pi_users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `pi_scope_violations` (
  `Seq` bigint UNSIGNED NOT NULL DEFAULT (UUID_SHORT()),
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `clinic_id` int UNSIGNED NOT NULL,
  `user_id` int UNSIGNED DEFAULT NULL,
  `role_code` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `route` varchar(80) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `violation_key` varchar(80) COLLATE utf8mb4_unicode_ci NOT NULL,
  `sql_fingerprint` char(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `details` varchar(600) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` bigint UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_scope_violations_clinic_id` (`clinic_id`,`id`),
  UNIQUE KEY `uq_scope_violations_seq` (`Seq`),
  KEY `idx_scope_violations_key` (`violation_key`,`created_at`),
  KEY `idx_scope_violations_recent` (`created_at`,`id`),
  KEY `idx_scope_violations_clinic_created` (`clinic_id`,`created_at`,`id`),
  KEY `idx_fk_scope_violations_user_id` (`user_id`),
  CONSTRAINT `fk_scope_violations_clinic` FOREIGN KEY (`clinic_id`) REFERENCES `pi_clinics` (`id`),
  CONSTRAINT `fk_scope_violations_user` FOREIGN KEY (`user_id`) REFERENCES `pi_users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `pi_subscription_payments` (
  `Seq` bigint UNSIGNED NOT NULL DEFAULT (UUID_SHORT()),
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `clinic_id` int UNSIGNED NOT NULL,
  `created_by` int UNSIGNED DEFAULT NULL,
  `amount_cents` int UNSIGNED NOT NULL DEFAULT '0',
  `status` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'pending_admin',
  `trust_release` tinyint(1) NOT NULL DEFAULT '1',
  `account_self` tinyint(1) NOT NULL DEFAULT '0',
  `account_holder_name` varchar(180) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `proof_path` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `applied_until` bigint UNSIGNED DEFAULT NULL,
  `reviewed_by` int UNSIGNED DEFAULT NULL,
  `reviewed_at` bigint UNSIGNED DEFAULT NULL,
  `review_note` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` bigint UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_subscription_payments_clinic_id` (`clinic_id`,`id`),
  UNIQUE KEY `uq_subscription_payments_seq` (`Seq`),
  KEY `idx_subscription_review` (`reviewed_at`,`status`),
  KEY `idx_sub_payments_clinic_status` (`clinic_id`,`status`,`id`),
  KEY `idx_sub_payments_admin` (`status`,`created_at`,`clinic_id`),
  KEY `idx_sub_payments_clinic_created_status` (`clinic_id`,`created_at`,`status`,`id`),
  KEY `idx_fk_subscription_payments_created_by` (`created_by`),
  KEY `idx_fk_subscription_payments_reviewed_by` (`reviewed_by`),
  CONSTRAINT `fk_sp_clinic` FOREIGN KEY (`clinic_id`) REFERENCES `pi_clinics` (`id`),
  CONSTRAINT `fk_sub_pay_created_by` FOREIGN KEY (`created_by`) REFERENCES `pi_users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_sub_pay_reviewed_by` FOREIGN KEY (`reviewed_by`) REFERENCES `pi_users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `pi_tasks` (
  `Seq` bigint UNSIGNED NOT NULL DEFAULT (UUID_SHORT()),
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `clinic_id` int UNSIGNED NOT NULL,
  `title` varchar(180) COLLATE utf8mb4_unicode_ci NOT NULL,
  `target_scope` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'clinic',
  `target_role` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `target_user_id` int UNSIGNED DEFAULT NULL,
  `assigned_to` int UNSIGNED DEFAULT NULL,
  `started_by` int UNSIGNED DEFAULT NULL,
  `started_at` bigint UNSIGNED DEFAULT NULL,
  `status` varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'aberta',
  `due_at` bigint UNSIGNED DEFAULT NULL,
  `completed_by` int UNSIGNED DEFAULT NULL,
  `completed_at` bigint UNSIGNED DEFAULT NULL,
  `created_by` int UNSIGNED DEFAULT NULL,
  `created_at` bigint UNSIGNED NOT NULL DEFAULT '0',
  `updated_at` bigint UNSIGNED DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_tasks_clinic_id` (`clinic_id`,`id`),
  UNIQUE KEY `uq_tasks_seq` (`Seq`),
  KEY `idx_tasks_role` (`clinic_id`,`target_scope`,`target_role`,`assigned_to`,`status`,`due_at`,`id`),
  KEY `idx_tasks_clinic_queue` (`clinic_id`,`target_scope`,`assigned_to`,`status`,`due_at`,`id`),
  KEY `idx_tasks_status_due` (`clinic_id`,`status`,`due_at`,`id`),
  KEY `idx_tasks_created` (`clinic_id`,`created_at`,`id`),
  KEY `idx_tasks_clinic_assignee_status_due` (`clinic_id`,`assigned_to`,`status`,`due_at`,`id`),
  KEY `idx_fk_tasks_assigned_to` (`assigned_to`),
  KEY `idx_fk_tasks_started_by` (`started_by`),
  KEY `idx_fk_tasks_completed_by` (`completed_by`),
  KEY `idx_fk_tasks_created_by` (`created_by`),
  CONSTRAINT `fk_tasks_assigned_to` FOREIGN KEY (`assigned_to`) REFERENCES `pi_users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_tasks_clinic` FOREIGN KEY (`clinic_id`) REFERENCES `pi_clinics` (`id`),
  CONSTRAINT `fk_tasks_completed_by` FOREIGN KEY (`completed_by`) REFERENCES `pi_users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_tasks_created_by` FOREIGN KEY (`created_by`) REFERENCES `pi_users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_tasks_started_by` FOREIGN KEY (`started_by`) REFERENCES `pi_users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `pi_user_devices` (
  `Seq` bigint UNSIGNED NOT NULL DEFAULT (UUID_SHORT()),
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` int UNSIGNED NOT NULL,
  `device_hash` char(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `device_label` varchar(160) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `device_platform` varchar(120) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `device_meta` text COLLATE utf8mb4_unicode_ci,
  `user_agent_hash` char(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `token_hash` char(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `scope` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'clinic',
  `clinic_role_id` bigint UNSIGNED DEFAULT NULL,
  `clinic_id` int UNSIGNED DEFAULT NULL,
  `role_code` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `last_route` varchar(80) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `last_ip` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `first_seen_at` bigint UNSIGNED NOT NULL DEFAULT '0',
  `last_seen_at` bigint UNSIGNED NOT NULL DEFAULT '0',
  `expires_at` bigint UNSIGNED NOT NULL DEFAULT '0',
  `revoked_at` bigint UNSIGNED DEFAULT NULL,
  `logout_at` bigint UNSIGNED DEFAULT NULL,
  `created_at` bigint UNSIGNED NOT NULL DEFAULT '0',
  `updated_at` bigint UNSIGNED DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_user_device_hash` (`user_id`,`device_hash`),
  UNIQUE KEY `uq_user_devices_seq` (`Seq`),
  UNIQUE KEY `uq_user_devices_clinic_id` (`clinic_id`,`id`),
  KEY `idx_user_devices_token` (`user_id`,`device_hash`,`expires_at`),
  KEY `idx_user_devices_active` (`user_id`,`revoked_at`,`expires_at`),
  KEY `idx_user_devices_seen` (`user_id`,`last_seen_at`),
  CONSTRAINT `fk_user_devices_clinic` FOREIGN KEY (`clinic_id`) REFERENCES `pi_clinics` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_user_devices_user` FOREIGN KEY (`user_id`) REFERENCES `pi_users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `pi_user_roles` (
  `Seq` bigint UNSIGNED NOT NULL DEFAULT (UUID_SHORT()),
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` int UNSIGNED NOT NULL,
  `clinic_id` int UNSIGNED NOT NULL,
  `role_code` varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL,
  `is_owner` tinyint(1) NOT NULL DEFAULT '0',
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` bigint UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_user_clinic_role` (`user_id`,`clinic_id`,`role_code`),
  UNIQUE KEY `uq_user_roles_clinic_id` (`clinic_id`,`id`),
  UNIQUE KEY `uq_user_roles_seq` (`Seq`),
  KEY `idx_uc_user` (`user_id`,`active`),
  KEY `idx_uc_clinic_role` (`clinic_id`,`role_code`,`active`),
  KEY `idx_uc_clinic_active_role_user` (`clinic_id`,`active`,`role_code`,`user_id`),
  CONSTRAINT `fk_uc_clinic` FOREIGN KEY (`clinic_id`) REFERENCES `pi_clinics` (`id`),
  CONSTRAINT `fk_uc_user` FOREIGN KEY (`user_id`) REFERENCES `pi_users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `pi_user_work_hours` (
  `Seq` bigint UNSIGNED NOT NULL DEFAULT (UUID_SHORT()),
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `clinic_id` int UNSIGNED NOT NULL,
  `user_id` int UNSIGNED NOT NULL,
  `weekday` tinyint UNSIGNED NOT NULL,
  `active` tinyint(1) NOT NULL DEFAULT '0',
  `start_time` time DEFAULT NULL,
  `end_time` time DEFAULT NULL,
  `updated_by` int UNSIGNED DEFAULT NULL,
  `updated_at` bigint UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_user_work_day` (`clinic_id`,`user_id`,`weekday`),
  UNIQUE KEY `uq_user_work_hours_clinic_id` (`clinic_id`,`id`),
  UNIQUE KEY `uq_user_work_hours_seq` (`Seq`),
  KEY `idx_user_work_user` (`clinic_id`,`user_id`,`active`),
  KEY `idx_fk_user_work_hours_user_id` (`user_id`),
  KEY `idx_fk_user_work_hours_updated_by` (`updated_by`),
  CONSTRAINT `fk_user_work_hours_clinic` FOREIGN KEY (`clinic_id`) REFERENCES `pi_clinics` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_user_work_hours_updated_by` FOREIGN KEY (`updated_by`) REFERENCES `pi_users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_user_work_hours_user` FOREIGN KEY (`user_id`) REFERENCES `pi_users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `pi_appointments` (
  `Seq` bigint UNSIGNED NOT NULL DEFAULT (UUID_SHORT()),
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `clinic_id` int UNSIGNED NOT NULL,
  `patient_link_id` bigint UNSIGNED DEFAULT NULL,
  `doctor_user_id` int UNSIGNED DEFAULT NULL,
  `start_at` bigint UNSIGNED NOT NULL DEFAULT '0',
  `end_at` bigint UNSIGNED NOT NULL DEFAULT '0',
  `status` varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'agendado',
  `reason` varchar(180) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `notes` text COLLATE utf8mb4_unicode_ci,
  `created_by` int UNSIGNED DEFAULT NULL,
  `arrived_at` bigint UNSIGNED DEFAULT NULL,
  `consultation_started_at` bigint UNSIGNED DEFAULT NULL,
  `consultation_finished_at` bigint UNSIGNED DEFAULT NULL,
  `cancel_reason` varchar(180) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `change_reason` varchar(180) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` bigint UNSIGNED NOT NULL DEFAULT '0',
  `updated_at` bigint UNSIGNED DEFAULT NULL,
  `procedure_id` bigint UNSIGNED DEFAULT NULL,
  `payment_status` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'prevista',
  `payment_method` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `payment_amount_cents` int UNSIGNED NOT NULL DEFAULT '0',
  `payment_confirmed_at` bigint UNSIGNED DEFAULT NULL,
  `revenue_id` bigint UNSIGNED DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_appointments_clinic_id` (`clinic_id`,`id`),
  UNIQUE KEY `uq_appointments_seq` (`Seq`),
  KEY `idx_appt_day` (`clinic_id`,`start_at`,`status`),
  KEY `idx_appt_doctor` (`clinic_id`,`doctor_user_id`,`start_at`),
  KEY `idx_appt_patient` (`clinic_id`,`patient_link_id`,`start_at`),
  KEY `idx_appt_started` (`clinic_id`,`doctor_user_id`,`consultation_started_at`),
  KEY `idx_appt_global_start` (`start_at`,`id`),
  KEY `idx_appt_arrived` (`clinic_id`,`arrived_at`,`status`),
  KEY `idx_appt_payment` (`clinic_id`,`payment_status`,`payment_confirmed_at`),
  KEY `idx_appt_clinic_window` (`clinic_id`,`start_at`,`end_at`,`status`),
  KEY `idx_appt_status_created` (`clinic_id`,`status`,`created_at`,`id`),
  KEY `idx_appt_clinic_status_start_id` (`clinic_id`,`status`,`start_at`,`id`),
  KEY `idx_appt_doctor_window` (`clinic_id`,`doctor_user_id`,`status`,`start_at`,`end_at`),
  KEY `idx_appt_patient_window` (`clinic_id`,`patient_link_id`,`status`,`start_at`,`id`),
  KEY `idx_fk_appointments_doctor_user_id` (`doctor_user_id`),
  KEY `idx_fk_appointments_created_by` (`created_by`),
  KEY `idx_fk_appointments_clinic_id_procedure_id` (`clinic_id`,`procedure_id`),
  CONSTRAINT `fk_appt_clinic` FOREIGN KEY (`clinic_id`) REFERENCES `pi_clinics` (`id`),
  CONSTRAINT `fk_appt_created_by` FOREIGN KEY (`created_by`) REFERENCES `pi_users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_appt_doctor` FOREIGN KEY (`doctor_user_id`) REFERENCES `pi_users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_appt_patient` FOREIGN KEY (`clinic_id`,`patient_link_id`) REFERENCES `pi_patients` (`clinic_id`, `id`),
  CONSTRAINT `fk_appt_procedure` FOREIGN KEY (`clinic_id`,`procedure_id`) REFERENCES `pi_procedures` (`clinic_id`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `pi_care` (
  `Seq` bigint UNSIGNED NOT NULL DEFAULT (UUID_SHORT()),
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `clinic_id` int UNSIGNED NOT NULL,
  `patient_link_id` bigint UNSIGNED NOT NULL,
  `appointment_id` bigint UNSIGNED DEFAULT NULL,
  `record_type` varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL,
  `title` varchar(180) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_by` int UNSIGNED DEFAULT NULL,
  `deleted_at` bigint UNSIGNED DEFAULT NULL,
  `deleted_by` int UNSIGNED DEFAULT NULL,
  `restored_at` bigint UNSIGNED DEFAULT NULL,
  `restored_by` int UNSIGNED DEFAULT NULL,
  `created_at` bigint UNSIGNED NOT NULL DEFAULT '0',
  `updated_at` bigint UNSIGNED DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_care_clinic_id` (`clinic_id`,`id`),
  UNIQUE KEY `uq_care_seq` (`Seq`),
  KEY `idx_care_patient` (`clinic_id`,`patient_link_id`,`created_at`,`id`),
  KEY `idx_care_type` (`clinic_id`,`record_type`,`created_at`,`id`),
  KEY `idx_care_appointment` (`clinic_id`,`appointment_id`,`id`),
  KEY `idx_care_patient_recent` (`clinic_id`,`patient_link_id`,`id`),
  KEY `idx_care_patient_type_active` (`clinic_id`,`patient_link_id`,`record_type`,`deleted_at`,`created_at`),
  KEY `idx_fk_care_created_by` (`created_by`),
  KEY `idx_fk_care_deleted_by` (`deleted_by`),
  KEY `idx_fk_care_restored_by` (`restored_by`),
  CONSTRAINT `fk_care_clinic` FOREIGN KEY (`clinic_id`) REFERENCES `pi_clinics` (`id`),
  CONSTRAINT `fk_care_created_by` FOREIGN KEY (`created_by`) REFERENCES `pi_users` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_care_deleted_by` FOREIGN KEY (`deleted_by`) REFERENCES `pi_users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_care_patient` FOREIGN KEY (`clinic_id`,`patient_link_id`) REFERENCES `pi_patients` (`clinic_id`, `id`),
  CONSTRAINT `fk_care_restored_by` FOREIGN KEY (`restored_by`) REFERENCES `pi_users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `pi_financial_expenses` (
  `Seq` bigint UNSIGNED NOT NULL DEFAULT (UUID_SHORT()),
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `clinic_id` int UNSIGNED NOT NULL,
  `counterparty_id` bigint UNSIGNED DEFAULT NULL,
  `account_id` bigint UNSIGNED DEFAULT NULL,
  `title` varchar(180) COLLATE utf8mb4_unicode_ci NOT NULL,
  `expense_category` varchar(80) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `document_number` varchar(80) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `competence_at` bigint UNSIGNED DEFAULT NULL,
  `amount_cents` int UNSIGNED NOT NULL DEFAULT '0',
  `status` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'prevista',
  `due_at` bigint UNSIGNED DEFAULT NULL,
  `paid_at` bigint UNSIGNED DEFAULT NULL,
  `payment_method` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `payment_method_id` bigint UNSIGNED DEFAULT NULL,
  `notes` text COLLATE utf8mb4_unicode_ci,
  `created_by` int UNSIGNED DEFAULT NULL,
  `updated_by` int UNSIGNED DEFAULT NULL,
  `created_at` bigint UNSIGNED NOT NULL DEFAULT '0',
  `updated_at` bigint UNSIGNED DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_financial_expenses_clinic_id` (`clinic_id`,`id`),
  UNIQUE KEY `uq_financial_expenses_seq` (`Seq`),
  KEY `idx_fin_exp_counterparty` (`clinic_id`,`counterparty_id`,`due_at`),
  KEY `idx_fin_exp_category` (`clinic_id`,`expense_category`,`due_at`),
  KEY `idx_fin_exp_status_due` (`clinic_id`,`status`,`due_at`,`amount_cents`),
  KEY `idx_fin_exp_operacional` (`clinic_id`,`status`,`due_at`,`paid_at`,`account_id`),
  KEY `idx_fin_exp_clinic_status_date` (`clinic_id`,`status`,`due_at`,`paid_at`,`id`),
  KEY `idx_fk_financial_expenses_created_by` (`created_by`),
  KEY `idx_fk_financial_expenses_updated_by` (`updated_by`),
  KEY `idx_fk_financial_expenses_clinic_id_account_id` (`clinic_id`,`account_id`),
  KEY `idx_fk_financial_expenses_clinic_id_payment_method_id` (`clinic_id`,`payment_method_id`),
  CONSTRAINT `fk_fin_exp_account` FOREIGN KEY (`clinic_id`,`account_id`) REFERENCES `pi_financial_accounts` (`clinic_id`, `id`),
  CONSTRAINT `fk_fin_exp_clinic` FOREIGN KEY (`clinic_id`) REFERENCES `pi_clinics` (`id`),
  CONSTRAINT `fk_fin_exp_counterparty` FOREIGN KEY (`clinic_id`,`counterparty_id`) REFERENCES `pi_financial_counterparties` (`clinic_id`, `id`),
  CONSTRAINT `fk_fin_exp_created_by` FOREIGN KEY (`created_by`) REFERENCES `pi_users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_fin_exp_method` FOREIGN KEY (`clinic_id`,`payment_method_id`) REFERENCES `pi_financial_payment_methods` (`clinic_id`, `id`),
  CONSTRAINT `fk_fin_exp_updated_by` FOREIGN KEY (`updated_by`) REFERENCES `pi_users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `pi_financial_locations` (
  `Seq` bigint UNSIGNED NOT NULL DEFAULT (UUID_SHORT()),
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `clinic_id` int UNSIGNED NOT NULL,
  `location_type` varchar(24) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name` varchar(120) COLLATE utf8mb4_unicode_ci NOT NULL,
  `user_id` int UNSIGNED DEFAULT NULL,
  `account_id` bigint UNSIGNED DEFAULT NULL,
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `drawer_lock_status` varchar(24) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'unlocked',
  `drawer_locked_business_date` bigint UNSIGNED DEFAULT NULL,
  `drawer_locked_at` bigint UNSIGNED DEFAULT NULL,
  `drawer_unlock_at` bigint UNSIGNED DEFAULT NULL,
  `drawer_unlocked_at` bigint UNSIGNED DEFAULT NULL,
  `drawer_reviewed_by` int UNSIGNED DEFAULT NULL,
  `drawer_reviewed_at` bigint UNSIGNED DEFAULT NULL,
  `drawer_review_notes` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_by` int UNSIGNED DEFAULT NULL,
  `created_at` bigint UNSIGNED NOT NULL DEFAULT '0',
  `updated_at` bigint UNSIGNED DEFAULT NULL,
  `location_identity` varchar(96) COLLATE utf8mb4_unicode_ci GENERATED ALWAYS AS ((case `location_type` when _utf8mb4'bank_account' then concat(_utf8mb4'account:',cast(`account_id` as char charset utf8mb4)) when _utf8mb4'admin_safe' then _utf8mb4'admin_safe' else NULL end)) STORED,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_financial_locations_clinic_id` (`clinic_id`,`id`),
  UNIQUE KEY `uq_fin_location_pos_user` (`clinic_id`,`location_type`,`user_id`),
  UNIQUE KEY `uq_fin_location_bank_account` (`clinic_id`,`location_type`,`account_id`),
  UNIQUE KEY `uq_financial_locations_seq` (`Seq`),
  UNIQUE KEY `uq_fin_location_identity` (`clinic_id`,`location_identity`),
  KEY `idx_fin_locations_scope` (`clinic_id`,`location_type`,`active`,`name`),
  KEY `idx_fin_locations_user` (`clinic_id`,`user_id`,`active`),
  KEY `idx_fk_financial_locations_user_id` (`user_id`),
  KEY `idx_fk_financial_locations_drawer_reviewed_by` (`drawer_reviewed_by`),
  KEY `idx_fk_financial_locations_created_by` (`created_by`),
  KEY `idx_fk_financial_locations_clinic_id_account_id` (`clinic_id`,`account_id`),
  CONSTRAINT `fk_fin_locations_account` FOREIGN KEY (`clinic_id`,`account_id`) REFERENCES `pi_financial_accounts` (`clinic_id`, `id`),
  CONSTRAINT `fk_fin_locations_clinic` FOREIGN KEY (`clinic_id`) REFERENCES `pi_clinics` (`id`),
  CONSTRAINT `fk_fin_locations_created_by` FOREIGN KEY (`created_by`) REFERENCES `pi_users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_fin_locations_reviewed_by` FOREIGN KEY (`drawer_reviewed_by`) REFERENCES `pi_users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_fin_locations_user` FOREIGN KEY (`user_id`) REFERENCES `pi_users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `pi_financial_transfers` (
  `Seq` bigint UNSIGNED NOT NULL DEFAULT (UUID_SHORT()),
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `clinic_id` int UNSIGNED NOT NULL,
  `account_from_id` bigint UNSIGNED NOT NULL,
  `account_to_id` bigint UNSIGNED NOT NULL,
  `amount_cents` int UNSIGNED NOT NULL,
  `transfer_at` bigint UNSIGNED NOT NULL DEFAULT '0',
  `notes` varchar(220) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_by` int UNSIGNED DEFAULT NULL,
  `created_at` bigint UNSIGNED NOT NULL DEFAULT '0',
  `updated_at` bigint UNSIGNED DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_financial_transfers_clinic_id` (`clinic_id`,`id`),
  UNIQUE KEY `uq_financial_transfers_seq` (`Seq`),
  KEY `idx_fin_transfers_scope` (`clinic_id`,`transfer_at`,`id`),
  KEY `idx_fin_transfers_from` (`clinic_id`,`account_from_id`,`transfer_at`),
  KEY `idx_fin_transfers_to` (`clinic_id`,`account_to_id`,`transfer_at`),
  KEY `idx_fk_financial_transfers_created_by` (`created_by`),
  CONSTRAINT `fk_fin_transfer_created_by` FOREIGN KEY (`created_by`) REFERENCES `pi_users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_fin_transfer_from` FOREIGN KEY (`clinic_id`,`account_from_id`) REFERENCES `pi_financial_accounts` (`clinic_id`, `id`),
  CONSTRAINT `fk_fin_transfer_to` FOREIGN KEY (`clinic_id`,`account_to_id`) REFERENCES `pi_financial_accounts` (`clinic_id`, `id`),
  CONSTRAINT `fk_fin_transfers_clinic` FOREIGN KEY (`clinic_id`) REFERENCES `pi_clinics` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `pi_lead_events` (
  `Seq` bigint UNSIGNED NOT NULL DEFAULT (UUID_SHORT()),
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `clinic_id` int UNSIGNED NOT NULL,
  `lead_id` bigint UNSIGNED NOT NULL,
  `event_type` varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'contato',
  `stage_from` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `stage_to` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `phone` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `source` varchar(80) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `interest` varchar(180) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `next_action_at` bigint UNSIGNED DEFAULT NULL,
  `body` text COLLATE utf8mb4_unicode_ci,
  `created_by` int UNSIGNED DEFAULT NULL,
  `created_at` bigint UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_lead_events_clinic_id` (`clinic_id`,`id`),
  UNIQUE KEY `uq_lead_events_seq` (`Seq`),
  KEY `idx_lead_events_scope` (`clinic_id`,`lead_id`,`created_at`,`id`),
  KEY `idx_lead_events_recent` (`clinic_id`,`created_at`,`id`),
  KEY `idx_fk_lead_events_created_by` (`created_by`),
  CONSTRAINT `fk_lead_events_clinic` FOREIGN KEY (`clinic_id`) REFERENCES `pi_clinics` (`id`),
  CONSTRAINT `fk_lead_events_created_by` FOREIGN KEY (`created_by`) REFERENCES `pi_users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_lead_events_lead` FOREIGN KEY (`clinic_id`,`lead_id`) REFERENCES `pi_leads` (`clinic_id`, `id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `pi_maestro_executions` (
  `Seq` bigint UNSIGNED NOT NULL DEFAULT (UUID_SHORT()),
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `clinic_id` int UNSIGNED NOT NULL,
  `rule_id` bigint UNSIGNED NOT NULL,
  `source_entity` varchar(60) COLLATE utf8mb4_unicode_ci NOT NULL,
  `source_entity_id` varchar(80) COLLATE utf8mb4_unicode_ci NOT NULL,
  `action_key` varchar(120) COLLATE utf8mb4_unicode_ci NOT NULL,
  `action_entity` varchar(60) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `action_entity_id` varchar(80) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'created',
  `message` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `executed_at` bigint UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_maestro_once` (`rule_id`,`source_entity`,`source_entity_id`,`action_key`),
  UNIQUE KEY `uq_maestro_executions_clinic_id` (`clinic_id`,`id`),
  UNIQUE KEY `uq_maestro_executions_seq` (`Seq`),
  KEY `idx_maestro_exec_rule` (`clinic_id`,`rule_id`,`executed_at`,`id`),
  KEY `idx_maestro_exec_source` (`clinic_id`,`source_entity`,`source_entity_id`),
  KEY `idx_maestro_exec_recent` (`executed_at`,`status`,`id`),
  CONSTRAINT `fk_maestro_exec_clinic` FOREIGN KEY (`clinic_id`) REFERENCES `pi_clinics` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_maestro_exec_rule` FOREIGN KEY (`clinic_id`,`rule_id`) REFERENCES `pi_maestro_rules` (`clinic_id`, `id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `pi_notice_reads` (
  `Seq` bigint UNSIGNED NOT NULL DEFAULT (UUID_SHORT()),
  `notice_id` bigint UNSIGNED NOT NULL,
  `user_id` int UNSIGNED NOT NULL,
  `read_at` bigint UNSIGNED DEFAULT NULL,
  `ack_at` bigint UNSIGNED DEFAULT NULL,
  `hidden_at` bigint UNSIGNED DEFAULT NULL,
  PRIMARY KEY (`notice_id`,`user_id`),
  UNIQUE KEY `uq_notice_reads_seq` (`Seq`),
  KEY `idx_notice_user` (`user_id`,`hidden_at`,`ack_at`),
  CONSTRAINT `fk_nr_notice` FOREIGN KEY (`notice_id`) REFERENCES `pi_notices` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_nr_user` FOREIGN KEY (`user_id`) REFERENCES `pi_users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `pi_patient_guardians` (
  `Seq` bigint UNSIGNED NOT NULL DEFAULT (UUID_SHORT()),
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `clinic_id` int UNSIGNED NOT NULL,
  `patient_link_id` bigint UNSIGNED NOT NULL,
  `full_name` varchar(160) COLLATE utf8mb4_unicode_ci NOT NULL,
  `cpf` char(11) COLLATE utf8mb4_unicode_ci NOT NULL,
  `relationship` varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL,
  `phone` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `email` varchar(160) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `document_note` varchar(180) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `notes` text COLLATE utf8mb4_unicode_ci,
  `is_primary` tinyint(1) NOT NULL DEFAULT '0',
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `created_by` int UNSIGNED DEFAULT NULL,
  `created_at` bigint UNSIGNED NOT NULL DEFAULT '0',
  `updated_at` bigint UNSIGNED DEFAULT NULL,
  `active_primary_key` bigint UNSIGNED GENERATED ALWAYS AS ((case when ((`active` = 1) and (`is_primary` = 1)) then `patient_link_id` else NULL end)) STORED,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_patient_guardian_cpf` (`clinic_id`,`patient_link_id`,`cpf`),
  UNIQUE KEY `uq_patient_guardians_clinic_id` (`clinic_id`,`id`),
  UNIQUE KEY `uq_patient_guardians_seq` (`Seq`),
  UNIQUE KEY `uq_guardian_one_primary` (`clinic_id`,`active_primary_key`),
  KEY `idx_patient_guardians` (`clinic_id`,`patient_link_id`,`active`,`is_primary`),
  KEY `idx_fk_patient_guardians_created_by` (`created_by`),
  CONSTRAINT `fk_patient_guardians_clinic` FOREIGN KEY (`clinic_id`) REFERENCES `pi_clinics` (`id`),
  CONSTRAINT `fk_patient_guardians_created_by` FOREIGN KEY (`created_by`) REFERENCES `pi_users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_patient_guardians_patient` FOREIGN KEY (`clinic_id`,`patient_link_id`) REFERENCES `pi_patients` (`clinic_id`, `id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `pi_patient_tabs` (
  `Seq` bigint UNSIGNED NOT NULL DEFAULT (UUID_SHORT()),
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `clinic_id` int UNSIGNED NOT NULL,
  `patient_link_id` bigint UNSIGNED NOT NULL,
  `label` varchar(80) COLLATE utf8mb4_unicode_ci NOT NULL,
  `icon_name` varchar(60) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'clinical_notes',
  `sort_order` smallint UNSIGNED NOT NULL DEFAULT '10',
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `created_by` int UNSIGNED DEFAULT NULL,
  `created_at` bigint UNSIGNED NOT NULL DEFAULT '0',
  `updated_at` bigint UNSIGNED DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_patient_tab_label` (`clinic_id`,`patient_link_id`,`label`),
  UNIQUE KEY `uq_patient_tabs_clinic_id` (`clinic_id`,`id`),
  UNIQUE KEY `uq_patient_tabs_seq` (`Seq`),
  KEY `idx_patient_tabs` (`clinic_id`,`patient_link_id`,`active`,`sort_order`,`id`),
  KEY `idx_fk_patient_tabs_created_by` (`created_by`),
  CONSTRAINT `fk_patient_tabs_clinic` FOREIGN KEY (`clinic_id`) REFERENCES `pi_clinics` (`id`),
  CONSTRAINT `fk_patient_tabs_created_by` FOREIGN KEY (`created_by`) REFERENCES `pi_users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_patient_tabs_patient` FOREIGN KEY (`clinic_id`,`patient_link_id`) REFERENCES `pi_patients` (`clinic_id`, `id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `pi_task_comments` (
  `Seq` bigint UNSIGNED NOT NULL DEFAULT (UUID_SHORT()),
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `clinic_id` int UNSIGNED NOT NULL,
  `task_id` bigint UNSIGNED NOT NULL,
  `user_id` int UNSIGNED DEFAULT NULL,
  `body` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `edited_by` int UNSIGNED DEFAULT NULL,
  `updated_at` bigint UNSIGNED DEFAULT NULL,
  `deleted_at` bigint UNSIGNED DEFAULT NULL,
  `deleted_by` int UNSIGNED DEFAULT NULL,
  `created_at` bigint UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_task_comments_clinic_id` (`clinic_id`,`id`),
  UNIQUE KEY `uq_task_comments_seq` (`Seq`),
  KEY `idx_task_comments_task` (`clinic_id`,`task_id`,`deleted_at`,`created_at`),
  KEY `idx_task_comments_user` (`clinic_id`,`user_id`,`created_at`),
  KEY `idx_fk_task_comments_edited_by` (`edited_by`),
  KEY `idx_fk_task_comments_deleted_by` (`deleted_by`),
  KEY `idx_fk_task_comments_user_id` (`user_id`),
  CONSTRAINT `fk_task_comments_clinic` FOREIGN KEY (`clinic_id`) REFERENCES `pi_clinics` (`id`),
  CONSTRAINT `fk_task_comments_deleted_by` FOREIGN KEY (`deleted_by`) REFERENCES `pi_users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_task_comments_edited_by` FOREIGN KEY (`edited_by`) REFERENCES `pi_users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_task_comments_task` FOREIGN KEY (`clinic_id`,`task_id`) REFERENCES `pi_tasks` (`clinic_id`, `id`) ON DELETE CASCADE,
  CONSTRAINT `fk_task_comments_user` FOREIGN KEY (`user_id`) REFERENCES `pi_users` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `pi_task_events` (
  `Seq` bigint UNSIGNED NOT NULL DEFAULT (UUID_SHORT()),
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `clinic_id` int UNSIGNED NOT NULL,
  `task_id` bigint UNSIGNED NOT NULL,
  `event_key` varchar(60) COLLATE utf8mb4_unicode_ci NOT NULL,
  `actor_user_id` int UNSIGNED DEFAULT NULL,
  `from_status` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `to_status` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `note` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` bigint UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_task_events_clinic_id` (`clinic_id`,`id`),
  UNIQUE KEY `uq_task_events_seq` (`Seq`),
  KEY `idx_task_events_task` (`clinic_id`,`task_id`,`created_at`,`id`),
  KEY `idx_task_events_actor` (`clinic_id`,`actor_user_id`,`created_at`,`id`),
  KEY `idx_fk_task_events_actor_user_id` (`actor_user_id`),
  CONSTRAINT `fk_task_events_actor` FOREIGN KEY (`actor_user_id`) REFERENCES `pi_users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_task_events_clinic` FOREIGN KEY (`clinic_id`) REFERENCES `pi_clinics` (`id`),
  CONSTRAINT `fk_task_events_task` FOREIGN KEY (`clinic_id`,`task_id`) REFERENCES `pi_tasks` (`clinic_id`, `id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `pi_care_content` (
  `Seq` bigint UNSIGNED NOT NULL DEFAULT (UUID_SHORT()),
  `care_id` bigint UNSIGNED NOT NULL,
  `clinic_id` int UNSIGNED NOT NULL,
  `content` mediumtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `updated_at` bigint UNSIGNED DEFAULT NULL,
  PRIMARY KEY (`care_id`),
  UNIQUE KEY `uq_care_content_seq` (`Seq`),
  KEY `idx_care_content_clinic` (`clinic_id`,`care_id`),
  CONSTRAINT `fk_care_content_care` FOREIGN KEY (`clinic_id`,`care_id`) REFERENCES `pi_care` (`clinic_id`, `id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `pi_care_versions` (
  `Seq` bigint UNSIGNED NOT NULL DEFAULT (UUID_SHORT()),
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `care_id` bigint UNSIGNED NOT NULL,
  `clinic_id` int UNSIGNED NOT NULL,
  `patient_link_id` bigint UNSIGNED NOT NULL,
  `old_record_type` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `old_title` varchar(160) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `old_content` mediumtext COLLATE utf8mb4_unicode_ci,
  `changed_by` int UNSIGNED DEFAULT NULL,
  `change_reason` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` bigint UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_care_versions_clinic_id` (`clinic_id`,`id`),
  UNIQUE KEY `uq_care_versions_seq` (`Seq`),
  KEY `idx_care_versions_care` (`care_id`,`created_at`,`id`),
  KEY `idx_care_versions_patient` (`clinic_id`,`patient_link_id`,`created_at`,`id`),
  KEY `idx_fk_care_versions_clinic_id_care_id` (`clinic_id`,`care_id`),
  CONSTRAINT `fk_care_versions_care` FOREIGN KEY (`clinic_id`,`care_id`) REFERENCES `pi_care` (`clinic_id`, `id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `pi_cash_sessions` (
  `Seq` bigint UNSIGNED NOT NULL DEFAULT (UUID_SHORT()),
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `clinic_id` int UNSIGNED NOT NULL,
  `user_id` int UNSIGNED NOT NULL,
  `location_id` bigint UNSIGNED NOT NULL,
  `business_date` bigint UNSIGNED NOT NULL DEFAULT '0',
  `opened_at` bigint UNSIGNED DEFAULT NULL,
  `kept_closed_at` bigint UNSIGNED DEFAULT NULL,
  `opening_balance_cents` int NOT NULL DEFAULT '0',
  `closed_at` bigint UNSIGNED DEFAULT NULL,
  `expected_closing_cents` int NOT NULL DEFAULT '0',
  `declared_closing_cents` int NOT NULL DEFAULT '0',
  `keep_in_drawer_cents` int NOT NULL DEFAULT '0',
  `transfer_to_safe_cents` int NOT NULL DEFAULT '0',
  `difference_cents` int NOT NULL DEFAULT '0',
  `status` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'open',
  `closing_notes` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `reviewed_by` int UNSIGNED DEFAULT NULL,
  `reviewed_at` bigint UNSIGNED DEFAULT NULL,
  `review_status` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `review_notes` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` bigint UNSIGNED NOT NULL DEFAULT '0',
  `updated_at` bigint UNSIGNED DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_cash_session_day` (`clinic_id`,`user_id`,`business_date`),
  UNIQUE KEY `uq_cash_sessions_clinic_id` (`clinic_id`,`id`),
  UNIQUE KEY `uq_cash_sessions_seq` (`Seq`),
  KEY `idx_cash_sessions_status` (`clinic_id`,`status`,`business_date`,`id`),
  KEY `idx_cash_sessions_user` (`clinic_id`,`user_id`,`business_date`,`status`),
  KEY `idx_fk_cash_sessions_user_id` (`user_id`),
  KEY `idx_fk_cash_sessions_reviewed_by` (`reviewed_by`),
  KEY `idx_fk_cash_sessions_clinic_id_location_id` (`clinic_id`,`location_id`),
  CONSTRAINT `fk_cash_sessions_clinic` FOREIGN KEY (`clinic_id`) REFERENCES `pi_clinics` (`id`),
  CONSTRAINT `fk_cash_sessions_location` FOREIGN KEY (`clinic_id`,`location_id`) REFERENCES `pi_financial_locations` (`clinic_id`, `id`),
  CONSTRAINT `fk_cash_sessions_reviewed_by` FOREIGN KEY (`reviewed_by`) REFERENCES `pi_users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_cash_sessions_user` FOREIGN KEY (`user_id`) REFERENCES `pi_users` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `pi_documents` (
  `Seq` bigint UNSIGNED NOT NULL DEFAULT (UUID_SHORT()),
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `clinic_id` int UNSIGNED NOT NULL,
  `template_id` bigint UNSIGNED DEFAULT NULL,
  `patient_link_id` bigint UNSIGNED DEFAULT NULL,
  `appointment_id` bigint UNSIGNED DEFAULT NULL,
  `context_json` json DEFAULT NULL,
  `issued_by` int UNSIGNED NOT NULL,
  `type_key` varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'declaracao',
  `title` varchar(180) COLLATE utf8mb4_unicode_ci NOT NULL,
  `content` mediumtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `document_status` varchar(24) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'emitido',
  `issued_at` bigint UNSIGNED NOT NULL DEFAULT '0',
  `confirmed_at` bigint UNSIGNED DEFAULT NULL,
  `cancelled_at` bigint UNSIGNED DEFAULT NULL,
  `cancelled_by` int UNSIGNED DEFAULT NULL,
  `updated_at` bigint UNSIGNED DEFAULT NULL,
  `document_sequence` int UNSIGNED DEFAULT NULL,
  `document_identifier` varchar(12) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_documents_clinic_id` (`clinic_id`,`id`),
  UNIQUE KEY `uq_docs_identifier` (`clinic_id`,`document_identifier`),
  UNIQUE KEY `uq_documents_seq` (`Seq`),
  KEY `idx_docs_clinic_date` (`clinic_id`,`issued_at`,`id`),
  KEY `idx_docs_patient` (`clinic_id`,`patient_link_id`,`issued_at`,`id`),
  KEY `idx_docs_issuer` (`clinic_id`,`issued_by`,`issued_at`,`id`),
  KEY `idx_docs_template` (`clinic_id`,`template_id`,`issued_at`,`id`),
  KEY `idx_docs_appointment` (`clinic_id`,`appointment_id`,`issued_at`,`id`),
  KEY `idx_docs_status` (`clinic_id`,`document_status`,`confirmed_at`,`updated_at`),
  KEY `idx_docs_recent_emitidos` (`clinic_id`,`document_status`,`issued_at`,`id`),
  KEY `idx_docs_clinic_patient_status` (`clinic_id`,`patient_link_id`,`document_status`,`updated_at`,`id`),
  KEY `idx_fk_documents_issued_by` (`issued_by`),
  KEY `idx_fk_documents_cancelled_by` (`cancelled_by`),
  CONSTRAINT `fk_docs_appointment` FOREIGN KEY (`clinic_id`,`appointment_id`) REFERENCES `pi_appointments` (`clinic_id`, `id`),
  CONSTRAINT `fk_docs_cancelled_by` FOREIGN KEY (`cancelled_by`) REFERENCES `pi_users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_docs_issued_by` FOREIGN KEY (`issued_by`) REFERENCES `pi_users` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_docs_patient` FOREIGN KEY (`clinic_id`,`patient_link_id`) REFERENCES `pi_patients` (`clinic_id`, `id`),
  CONSTRAINT `fk_docs_template` FOREIGN KEY (`clinic_id`,`template_id`) REFERENCES `pi_document_templates` (`clinic_id`, `id`),
  CONSTRAINT `fk_documents_clinic` FOREIGN KEY (`clinic_id`) REFERENCES `pi_clinics` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `pi_financial_location_users` (
  `Seq` bigint UNSIGNED NOT NULL DEFAULT (UUID_SHORT()),
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `clinic_id` int UNSIGNED NOT NULL,
  `location_id` bigint UNSIGNED NOT NULL,
  `user_id` int UNSIGNED NOT NULL,
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `created_by` int UNSIGNED DEFAULT NULL,
  `created_at` bigint UNSIGNED NOT NULL DEFAULT '0',
  `updated_at` bigint UNSIGNED DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_fin_location_user` (`clinic_id`,`location_id`,`user_id`),
  UNIQUE KEY `uq_financial_location_users_clinic_id` (`clinic_id`,`id`),
  UNIQUE KEY `uq_financial_location_users_seq` (`Seq`),
  KEY `idx_fin_location_users_user` (`clinic_id`,`user_id`,`active`),
  KEY `idx_fin_location_users_location` (`clinic_id`,`location_id`,`active`),
  KEY `idx_fk_financial_location_users_user_id` (`user_id`),
  KEY `idx_fk_financial_location_users_created_by` (`created_by`),
  CONSTRAINT `fk_fin_location_users_clinic` FOREIGN KEY (`clinic_id`) REFERENCES `pi_clinics` (`id`),
  CONSTRAINT `fk_fin_location_users_created_by` FOREIGN KEY (`created_by`) REFERENCES `pi_users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_fin_location_users_location` FOREIGN KEY (`clinic_id`,`location_id`) REFERENCES `pi_financial_locations` (`clinic_id`, `id`),
  CONSTRAINT `fk_fin_location_users_user` FOREIGN KEY (`user_id`) REFERENCES `pi_users` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `pi_financial_revenues` (
  `Seq` bigint UNSIGNED NOT NULL DEFAULT (UUID_SHORT()),
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `clinic_id` int UNSIGNED NOT NULL,
  `appointment_id` bigint UNSIGNED DEFAULT NULL,
  `procedure_id` bigint UNSIGNED DEFAULT NULL,
  `patient_link_id` bigint UNSIGNED DEFAULT NULL,
  `title` varchar(180) COLLATE utf8mb4_unicode_ci NOT NULL,
  `amount_cents` int UNSIGNED NOT NULL DEFAULT '0',
  `status` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'prevista',
  `payment_method` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `payment_method_id` bigint UNSIGNED DEFAULT NULL,
  `account_id` bigint UNSIGNED DEFAULT NULL,
  `expected_at` bigint UNSIGNED DEFAULT NULL,
  `received_at` bigint UNSIGNED DEFAULT NULL,
  `created_by` int UNSIGNED DEFAULT NULL,
  `updated_by` int UNSIGNED DEFAULT NULL,
  `created_at` bigint UNSIGNED NOT NULL DEFAULT '0',
  `updated_at` bigint UNSIGNED DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_financial_revenues_clinic_id` (`clinic_id`,`id`),
  UNIQUE KEY `uq_revenue_appointment` (`clinic_id`,`appointment_id`),
  UNIQUE KEY `uq_financial_revenues_seq` (`Seq`),
  KEY `idx_fin_rev_received` (`clinic_id`,`received_at`,`payment_method`),
  KEY `idx_fin_rev_payment_method` (`clinic_id`,`payment_method_id`),
  KEY `idx_fin_rev_status_hour` (`clinic_id`,`status`,`received_at`,`amount_cents`),
  KEY `idx_fin_rev_operacional` (`clinic_id`,`status`,`expected_at`,`received_at`,`account_id`),
  KEY `idx_fin_rev_clinic_status_date` (`clinic_id`,`status`,`expected_at`,`received_at`,`id`),
  KEY `idx_fk_financial_revenues_created_by` (`created_by`),
  KEY `idx_fk_financial_revenues_updated_by` (`updated_by`),
  KEY `idx_fk_financial_revenues_clinic_id_procedure_id` (`clinic_id`,`procedure_id`),
  KEY `idx_fk_financial_revenues_clinic_id_patient_link_id` (`clinic_id`,`patient_link_id`),
  KEY `idx_fk_financial_revenues_clinic_id_account_id` (`clinic_id`,`account_id`),
  CONSTRAINT `fk_fin_rev_account` FOREIGN KEY (`clinic_id`,`account_id`) REFERENCES `pi_financial_accounts` (`clinic_id`, `id`),
  CONSTRAINT `fk_fin_rev_appointment` FOREIGN KEY (`clinic_id`,`appointment_id`) REFERENCES `pi_appointments` (`clinic_id`, `id`),
  CONSTRAINT `fk_fin_rev_clinic` FOREIGN KEY (`clinic_id`) REFERENCES `pi_clinics` (`id`),
  CONSTRAINT `fk_fin_rev_created_by` FOREIGN KEY (`created_by`) REFERENCES `pi_users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_fin_rev_method` FOREIGN KEY (`clinic_id`,`payment_method_id`) REFERENCES `pi_financial_payment_methods` (`clinic_id`, `id`),
  CONSTRAINT `fk_fin_rev_patient` FOREIGN KEY (`clinic_id`,`patient_link_id`) REFERENCES `pi_patients` (`clinic_id`, `id`),
  CONSTRAINT `fk_fin_rev_procedure` FOREIGN KEY (`clinic_id`,`procedure_id`) REFERENCES `pi_procedures` (`clinic_id`, `id`),
  CONSTRAINT `fk_fin_rev_updated_by` FOREIGN KEY (`updated_by`) REFERENCES `pi_users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `pi_task_details` (
  `Seq` bigint UNSIGNED NOT NULL DEFAULT (UUID_SHORT()),
  `task_id` bigint UNSIGNED NOT NULL,
  `clinic_id` int UNSIGNED NOT NULL,
  `description` text COLLATE utf8mb4_unicode_ci,
  `patient_link_id` bigint UNSIGNED DEFAULT NULL,
  `appointment_id` bigint UNSIGNED DEFAULT NULL,
  `source_event` varchar(80) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `source_entity` varchar(60) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `source_entity_id` varchar(80) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`task_id`),
  UNIQUE KEY `uq_task_details_seq` (`Seq`),
  KEY `idx_task_details_patient` (`clinic_id`,`patient_link_id`,`task_id`),
  KEY `idx_task_details_appointment` (`clinic_id`,`appointment_id`,`task_id`),
  KEY `idx_task_details_source` (`clinic_id`,`source_entity`,`source_entity_id`),
  KEY `idx_task_details_source_ref` (`clinic_id`,`source_event`,`source_entity`,`source_entity_id`),
  KEY `idx_fk_task_details_clinic_id_task_id` (`clinic_id`,`task_id`),
  CONSTRAINT `fk_task_details_appointment` FOREIGN KEY (`clinic_id`,`appointment_id`) REFERENCES `pi_appointments` (`clinic_id`, `id`),
  CONSTRAINT `fk_task_details_clinic` FOREIGN KEY (`clinic_id`) REFERENCES `pi_clinics` (`id`),
  CONSTRAINT `fk_task_details_patient` FOREIGN KEY (`clinic_id`,`patient_link_id`) REFERENCES `pi_patients` (`clinic_id`, `id`),
  CONSTRAINT `fk_task_details_task` FOREIGN KEY (`clinic_id`,`task_id`) REFERENCES `pi_tasks` (`clinic_id`, `id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `pi_cash_closing_reviews` (
  `Seq` bigint UNSIGNED NOT NULL DEFAULT (UUID_SHORT()),
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `clinic_id` int UNSIGNED NOT NULL,
  `cash_session_id` bigint UNSIGNED NOT NULL,
  `reviewed_by` int UNSIGNED NOT NULL,
  `decision` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `expected_cents` int NOT NULL DEFAULT '0',
  `declared_cents` int NOT NULL DEFAULT '0',
  `approved_transfer_cents` int NOT NULL DEFAULT '0',
  `difference_cents` int NOT NULL DEFAULT '0',
  `notes` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` bigint UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_cash_closing_reviews_clinic_id` (`clinic_id`,`id`),
  UNIQUE KEY `uq_cash_closing_reviews_seq` (`Seq`),
  KEY `idx_cash_reviews_session` (`clinic_id`,`cash_session_id`,`created_at`,`id`),
  KEY `idx_cash_reviews_reviewer` (`clinic_id`,`reviewed_by`,`created_at`,`id`),
  KEY `idx_fk_cash_closing_reviews_reviewed_by` (`reviewed_by`),
  CONSTRAINT `fk_cash_reviews_clinic` FOREIGN KEY (`clinic_id`) REFERENCES `pi_clinics` (`id`),
  CONSTRAINT `fk_cash_reviews_session` FOREIGN KEY (`clinic_id`,`cash_session_id`) REFERENCES `pi_cash_sessions` (`clinic_id`, `id`),
  CONSTRAINT `fk_cash_reviews_user` FOREIGN KEY (`reviewed_by`) REFERENCES `pi_users` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `pi_document_pdfs` (
  `Seq` bigint UNSIGNED NOT NULL DEFAULT (UUID_SHORT()),
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `clinic_id` int UNSIGNED NOT NULL,
  `document_id` bigint UNSIGNED NOT NULL,
  `generated_by` int UNSIGNED DEFAULT NULL,
  `document_identifier` varchar(12) COLLATE utf8mb4_unicode_ci NOT NULL,
  `generated_unix` bigint UNSIGNED NOT NULL,
  `file_name` varchar(160) COLLATE utf8mb4_unicode_ci NOT NULL,
  `file_path` varchar(220) COLLATE utf8mb4_unicode_ci NOT NULL,
  `file_sha256` char(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `file_size` int UNSIGNED NOT NULL DEFAULT '0',
  `created_at` bigint UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_document_pdf_file` (`file_name`),
  UNIQUE KEY `uq_document_pdfs_clinic_id` (`clinic_id`,`id`),
  UNIQUE KEY `uq_document_pdfs_seq` (`Seq`),
  KEY `idx_document_pdfs_doc` (`clinic_id`,`document_id`,`generated_unix`),
  KEY `idx_document_pdfs_clinic_date` (`clinic_id`,`created_at`,`id`),
  KEY `idx_fk_document_pdfs_generated_by` (`generated_by`),
  CONSTRAINT `fk_document_pdfs_clinic` FOREIGN KEY (`clinic_id`) REFERENCES `pi_clinics` (`id`),
  CONSTRAINT `fk_document_pdfs_document` FOREIGN KEY (`clinic_id`,`document_id`) REFERENCES `pi_documents` (`clinic_id`, `id`) ON DELETE CASCADE,
  CONSTRAINT `fk_document_pdfs_generated_by` FOREIGN KEY (`generated_by`) REFERENCES `pi_users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `pi_financial_allocations` (
  `Seq` bigint UNSIGNED NOT NULL DEFAULT (UUID_SHORT()),
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `clinic_id` int UNSIGNED NOT NULL,
  `revenue_id` bigint UNSIGNED DEFAULT NULL,
  `expense_id` bigint UNSIGNED DEFAULT NULL,
  `account_id` bigint UNSIGNED DEFAULT NULL,
  `amount_cents` int UNSIGNED NOT NULL DEFAULT '0',
  `payment_method` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `allocated_at` bigint UNSIGNED NOT NULL DEFAULT '0',
  `created_by` int UNSIGNED DEFAULT NULL,
  `notes` varchar(220) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_financial_allocations_clinic_id` (`clinic_id`,`id`),
  UNIQUE KEY `uq_financial_allocations_seq` (`Seq`),
  KEY `idx_fin_alloc_scope` (`clinic_id`,`allocated_at`,`account_id`),
  KEY `idx_fk_financial_allocations_created_by` (`created_by`),
  KEY `idx_fk_financial_allocations_clinic_id_revenue_id` (`clinic_id`,`revenue_id`),
  KEY `idx_fk_financial_allocations_clinic_id_expense_id` (`clinic_id`,`expense_id`),
  KEY `idx_fk_financial_allocations_clinic_id_account_id` (`clinic_id`,`account_id`),
  CONSTRAINT `fk_fin_alloc_account` FOREIGN KEY (`clinic_id`,`account_id`) REFERENCES `pi_financial_accounts` (`clinic_id`, `id`),
  CONSTRAINT `fk_fin_alloc_clinic` FOREIGN KEY (`clinic_id`) REFERENCES `pi_clinics` (`id`),
  CONSTRAINT `fk_fin_alloc_created_by` FOREIGN KEY (`created_by`) REFERENCES `pi_users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_fin_alloc_expense` FOREIGN KEY (`clinic_id`,`expense_id`) REFERENCES `pi_financial_expenses` (`clinic_id`, `id`),
  CONSTRAINT `fk_fin_alloc_revenue` FOREIGN KEY (`clinic_id`,`revenue_id`) REFERENCES `pi_financial_revenues` (`clinic_id`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `pi_financial_movements` (
  `Seq` bigint UNSIGNED NOT NULL DEFAULT (UUID_SHORT()),
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `clinic_id` int UNSIGNED NOT NULL,
  `movement_type` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `status` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'confirmed',
  `amount_cents` int UNSIGNED NOT NULL,
  `payment_method` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `from_location_id` bigint UNSIGNED DEFAULT NULL,
  `to_location_id` bigint UNSIGNED DEFAULT NULL,
  `cash_session_id` bigint UNSIGNED DEFAULT NULL,
  `source_entity` varchar(60) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `source_id` bigint UNSIGNED DEFAULT NULL,
  `title` varchar(180) COLLATE utf8mb4_unicode_ci NOT NULL,
  `notes` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_by` int UNSIGNED DEFAULT NULL,
  `created_at` bigint UNSIGNED NOT NULL DEFAULT '0',
  `updated_at` bigint UNSIGNED DEFAULT NULL,
  `confirmed_by` int UNSIGNED DEFAULT NULL,
  `confirmed_at` bigint UNSIGNED DEFAULT NULL,
  `reviewed_by` int UNSIGNED DEFAULT NULL,
  `reviewed_at` bigint UNSIGNED DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_financial_movements_clinic_id` (`clinic_id`,`id`),
  UNIQUE KEY `uq_financial_movements_seq` (`Seq`),
  KEY `idx_fin_movements_scope` (`clinic_id`,`created_at`,`id`),
  KEY `idx_fin_movements_session` (`clinic_id`,`cash_session_id`,`created_at`,`id`),
  KEY `idx_fin_movements_from` (`clinic_id`,`from_location_id`,`status`,`created_at`),
  KEY `idx_fin_movements_to` (`clinic_id`,`to_location_id`,`status`,`created_at`),
  KEY `idx_fin_movements_source` (`clinic_id`,`source_entity`,`source_id`,`movement_type`),
  KEY `idx_fin_movements_status` (`clinic_id`,`status`,`movement_type`,`created_at`),
  KEY `idx_fk_financial_movements_created_by` (`created_by`),
  KEY `idx_fk_financial_movements_confirmed_by` (`confirmed_by`),
  KEY `idx_fk_financial_movements_reviewed_by` (`reviewed_by`),
  CONSTRAINT `fk_fin_movements_clinic` FOREIGN KEY (`clinic_id`) REFERENCES `pi_clinics` (`id`),
  CONSTRAINT `fk_fin_movements_confirmed_by` FOREIGN KEY (`confirmed_by`) REFERENCES `pi_users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_fin_movements_created_by` FOREIGN KEY (`created_by`) REFERENCES `pi_users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_fin_movements_from` FOREIGN KEY (`clinic_id`,`from_location_id`) REFERENCES `pi_financial_locations` (`clinic_id`, `id`),
  CONSTRAINT `fk_fin_movements_reviewed_by` FOREIGN KEY (`reviewed_by`) REFERENCES `pi_users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_fin_movements_session` FOREIGN KEY (`clinic_id`,`cash_session_id`) REFERENCES `pi_cash_sessions` (`clinic_id`, `id`),
  CONSTRAINT `fk_fin_movements_to` FOREIGN KEY (`clinic_id`,`to_location_id`) REFERENCES `pi_financial_locations` (`clinic_id`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
