<!DOCTYPE html><html lang="pt-BR"><head><meta charset="UTF-8"><meta name="robots" content="noindex,nofollow,noarchive"><meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no"><title>SOL/USDT – Painel</title><link rel="icon" id="favicon" href="data:,"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Space+Mono:wght@400;700&family=DM+Sans:opsz,wght@9..40,400;9..40,500;9..40,600;9..40,700&display=swap" rel="stylesheet"><link rel="stylesheet" href="css/style.css"></head><body>
<div class="container">
<div class="avatar-wrap"><div class="avatar" id="avatar" title="Editar carteira"><canvas id="avatarCanvas" width="36" height="36"></canvas></div></div>
<div id="marketDot" hidden></div><span id="marketStatus" hidden></span><span id="lastUpdate" hidden></span>
<div class="row-cards"><div class="card"><span class="label">Preço</span><span class="value" id="currentPrice">$ --</span><span class="change" id="change24h">--</span></div><div class="card"><span class="label">Volume</span><span class="value" id="volume24hValue">--</span><span class="change" id="volumeHourlyChange">--</span></div><div class="card"><span class="label">Total</span><span class="value" id="carteiraUsdValue">$ --</span><span class="change" id="carteiraUsdChange">--</span></div><div class="card" id="pnlCard"><span class="label" id="pnlLabel">Lucro</span><span class="value" id="pnlValue">R$ --</span><span class="change" id="pnlChange">--</span></div></div>
<div class="card analysis-card"><div class="bar-item"><div class="bar-track" id="priceBarTrack"><div class="bar-pointer" id="priceBarPointer" style="left:50%"></div></div><div class="bar-labels"><span id="priceMinValue">--</span><span id="priceBarValue" class="bar-center-value">--</span><span id="priceMaxValue">--</span></div></div><div class="bar-item"><div class="bar-track" id="volumeBarTrack"><div class="bar-pointer" id="volumeBarPointer" style="left:50%"></div></div><div class="bar-labels"><span id="volumeMinValue">--</span><span id="volumeBarValue" class="bar-center-value">--</span><span id="volumeMaxValue">--</span></div></div><div class="bar-item"><div class="bar-track" id="rsiBarTrack"><div class="rsi-zones"><div class="rsi-zone-1"></div><div class="rsi-zone-2"></div><div class="rsi-zone-3"></div></div><div class="rsi-ticks"><div class="rsi-tick" style="left:20%"></div><div class="rsi-tick" style="left:80%"></div></div><div class="bar-pointer" id="rsiBarPointer" style="left:50%"></div></div><div class="bar-labels"><span id="rsiBarValueNum">50,0</span><span id="rsiBarValueLabel">Neutro</span></div></div></div>
<div class="chart-card" id="chartCard"><canvas id="candleCanvas"></canvas></div>
</div>
<div class="modal-carteira" id="carteiraModal" aria-hidden="true"><div class="modal-content"><h2>Editar Carteira</h2><div class="field"><label>Integralizado (R$)</label><input id="inInteg" type="text" inputmode="decimal" value="0,00"></div><div class="field"><label>Saldo SOL</label><input id="inSol" type="text" inputmode="decimal" placeholder="0,0000"></div><div class="field"><label>Saldo USDC / USDT</label><input id="inUsdc" type="text" inputmode="decimal" placeholder="0,00"></div><div class="field"><label>Preço médio (USD) – opcional</label><input id="inPrecoMedio" type="text" inputmode="decimal" placeholder="0,00"></div><div class="btn-row"><button class="btn save" id="saveCarteiraBtn">Salvar</button><button class="btn" id="closeCarteiraBtn">Cancelar</button></div><div class="note" id="carteiraNote"></div></div></div>
<script src="js/app.js"></script></body></html>
