const setText=(el,value)=>{if(el&&el.textContent!==String(value))el.textContent=String(value)};
function setChange(el,p){if(!el)return;if(p==null||Number.isNaN(Number(p))){setText(el,'Aguardando...');el.className='change neutral';return}setText(el,formatPercent(p));el.className='change '+(Number(p)>=0?'up':'dn')}
function parseLocale(value){const raw=String(value??'').trim();if(!raw)return 0;const normalized=raw.includes(',')?raw.replace(/\./g,'').replace(',','.'):raw;const number=Number(normalized);return Number.isFinite(number)?number:0}
function sma(values,period){const out=[];let sum=0;for(let i=0;i<values.length;i++){sum+=Number(values[i]||0);if(i>=period)sum-=Number(values[i-period]||0);out.push(sum/Math.min(period,i+1))}return out}
function ema(values,period){if(!values.length)return[];const k=2/(period+1);let current=Number(values[0]||0);const out=[current];for(let i=1;i<values.length;i++){current=Number(values[i]||0)*k+current*(1-k);out.push(current)}return out}
function boll(closes,period=20,multiplier=2){const upper=[],middle=[],lower=[];let sum=0,sumSq=0;for(let i=0;i<closes.length;i++){const value=Number(closes[i]||0);sum+=value;sumSq+=value*value;if(i>=period){const old=Number(closes[i-period]||0);sum-=old;sumSq-=old*old}const n=Math.min(period,i+1);if(n<2){upper.push(null);middle.push(null);lower.push(null);continue}const avg=sum/n;const variance=Math.max(0,sumSq/n-avg*avg);const sd=Math.sqrt(variance);upper.push(avg+multiplier*sd);middle.push(avg);lower.push(avg-multiplier*sd)}return{upper,middle,lower}}
function calcRSI(closes,period=14){if(closes.length<period+1)return 50;let gains=0,losses=0;for(let i=closes.length-period;i<closes.length;i++){const diff=Number(closes[i])-Number(closes[i-1]);if(diff>=0)gains+=diff;else losses-=diff}if(losses===0)return 100;return 100-100/(1+gains/losses)}
function invalidate(mask=DIRTY_ALL){dirty|=mask;if(renderTimer)return;const wait=Math.max(0,125-(performance.now()-lastFrameAt));renderTimer=setTimeout(()=>requestAnimationFrame(flushRender),wait)}
function flushRender(){renderTimer=0;lastFrameAt=performance.now();const mask=dirty;dirty=0;if(mask&DIRTY_METRICS)renderMetrics();if(mask&DIRTY_CHART)drawChart();if(mask&DIRTY_MINI)renderMini();if(mask&DIRTY_AI)renderAiMetrics()}
function normalizedHourly(rows){const map=new Map();for(const row of rows||[]){const candle=Array.isArray(row)?{t:Number(row[0])/1000,o:Number(row[1]),h:Number(row[2]),l:Number(row[3]),c:Number(row[4]),v:Number(row[5])}:{t:Number(row.t),o:Number(row.o),h:Number(row.h),l:Number(row.l),c:Number(row.c),v:Number(row.v||0)};if([candle.t,candle.o,candle.h,candle.l,candle.c,candle.v].every(Number.isFinite))map.set(candle.t,candle)}return Array.from(map.values()).sort((a,b)=>a.t-b.t).slice(-96)}
function upsertHourly(candle){if(!candle||!Number.isFinite(candle.t))return;const last=state.hourly.at(-1);if(last&&last.t===candle.t)state.hourly[state.hourly.length-1]=candle;else if(!last||candle.t>last.t)state.hourly.push(candle);else{const index=state.hourly.findIndex(item=>item.t===candle.t);if(index>=0)state.hourly[index]=candle;else state.hourly.push(candle);state.hourly.sort((a,b)=>a.t-b.t)}state.hourly=state.hourly.slice(-96);state.marketRevision++}
function applyPrice(price){price=Number(price||0);if(!(price>0))return;state.previousPrice=state.currentPrice||price;state.currentPrice=price;state.perpsMarks.SOL=price;const last=state.hourly.at(-1);if(last){last.c=price;last.h=Math.max(last.h,price);last.l=Math.min(last.l,price)}invalidate(DIRTY_METRICS|DIRTY_CHART|DIRTY_MINI)}
function applyPerpsMark(symbol,bid,ask){bid=Number(bid||0);ask=Number(ask||0);const price=bid>0&&ask>0?(bid+ask)/2:bid>0?bid:ask,asset=String(symbol||'').replace(/USDT$/,'');if(!(price>0)||!Object.prototype.hasOwnProperty.call(state.perpsMarks,asset))return;state.perpsMarkAt[asset]=Date.now();if(asset==='SOL'){state.bestBid=bid;state.bestAsk=ask;applyPrice(price);return}state.perpsMarks[asset]=price;if(state.wallet.perpsPositions.some(position=>String(position?.asset||'').toUpperCase()===asset))invalidate(DIRTY_METRICS)}
function applyHourTicker(openPrice,eventTime=Date.now()){const price=Number(openPrice||0),at=Number(eventTime||0);if(!(price>0))return;state.hourAgoPrice=price;state.hourAgoPriceAt=at>0?at:Date.now();invalidate(DIRTY_METRICS)}
async function fetchWithTimeout(url,options={},timeout=8000){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),timeout);try{return await fetch(url,{...options,signal:controller.signal,cache:'no-store'})}finally{clearTimeout(timer)}}
async function fetchMarket(path){let lastError=null;for(const base of API_BASES){try{const response=await fetchWithTimeout(base+path,{},8000);if(!response.ok)throw new Error(String(response.status));return await response.json()}catch(error){lastError=error}}throw lastError||new Error('market_unavailable')}
async function refreshHistorical(){try{const rows=await fetchMarket('/api/v3/klines?symbol=SOLUSDT&interval=1h&limit=96');const candles=normalizedHourly(rows);if(candles.length){state.hourly=candles;state.marketRevision++;const last=candles.at(-1);if(!(state.currentPrice>0))state.currentPrice=last.c;if(!(state.previousPrice>0))state.previousPrice=state.currentPrice;state.perpsMarks.SOL=state.currentPrice;state.perpsMarkAt.SOL=Date.now();invalidate(DIRTY_METRICS|DIRTY_CHART|DIRTY_MINI)}}catch(error){console.warn('historical',error)}}
async function refreshHourTicker(){try{const row=await fetchMarket('/api/v3/ticker?symbol=SOLUSDT&windowSize=1h&type=MINI');applyHourTicker(row.openPrice,row.closeTime)}catch(error){console.warn('ticker-1h',error)}}
async function refreshPerpsMark(asset){asset=String(asset||'').toUpperCase();if(!Object.prototype.hasOwnProperty.call(state.perpsMarks,asset))return;try{const row=await fetchMarket(`/api/v3/ticker/bookTicker?symbol=${asset}USDT`);applyPerpsMark(asset+'USDT',row.bidPrice,row.askPrice)}catch(error){console.warn('ticker-'+asset.toLowerCase(),error)}}
async function refreshBookTicker(){return refreshPerpsMark('SOL')}
async function refreshActivePerpsMarks(){const assets=new Set(['SOL']);for(const position of state.wallet.perpsPositions){const asset=String(position?.asset||'').toUpperCase();if(Object.prototype.hasOwnProperty.call(state.perpsMarks,asset))assets.add(asset)}const now=Date.now(),tasks=[];for(const asset of assets){if(now-Number(state.perpsMarkAt[asset]||0)>15000)tasks.push(refreshPerpsMark(asset))}if(tasks.length)await Promise.allSettled(tasks)}
async function refreshUsdBrl(){try{const row=await fetchMarket('/api/v3/ticker/bookTicker?symbol=USDTBRL');applyUsdBrl(row.bidPrice,row.askPrice)}catch(error){console.warn('usdbrl',error)}}
function applyUsdBrl(bid,ask){bid=Number(bid||0);ask=Number(ask||0);const rate=bid>0&&ask>0?(bid+ask)/2:bid>0?bid:ask;if(rate>0){state.usdBrl=rate;localStorage.setItem('usd_brl_cache',String(rate));invalidate(DIRTY_METRICS)}}
function connectSocket(){if(state.socket&&state.socket.readyState<=1)return;const url='wss://stream.binance.com:9443/stream?streams=solusdt@bookTicker/btcusdt@bookTicker/ethusdt@bookTicker/solusdt@kline_1h/solusdt@ticker_1h/usdtbrl@bookTicker';try{const socket=new WebSocket(url);socket.onopen=()=>{state.socketBackoff=1000;state.lastSocketAt=Date.now()};socket.onmessage=event=>{state.lastSocketAt=Date.now();try{const packet=JSON.parse(event.data),data=packet.data||packet;if(data.e==='bookTicker'){if(data.s==='USDTBRL')applyUsdBrl(data.b,data.a);else applyPerpsMark(data.s,data.b,data.a);return}if(data.e==='1hTicker'&&data.s==='SOLUSDT'){applyHourTicker(data.o,data.C||data.E);return}if(data.e==='kline'&&data.k){const k=data.k;const candle={t:Number(k.t)/1000,o:Number(k.o),h:Number(k.h),l:Number(k.l),c:Number(k.c),v:Number(k.v)};if([candle.t,candle.o,candle.h,candle.l,candle.c,candle.v].every(Number.isFinite)){upsertHourly(candle);state.perpsMarkAt.SOL=Date.now();applyPrice(candle.c)}}}catch(error){console.warn('socket_message',error)}};socket.onclose=()=>{if(state.socket===socket)state.socket=null;const delay=state.socketBackoff;state.socketBackoff=Math.min(15000,state.socketBackoff*1.7);setTimeout(connectSocket,delay)};socket.onerror=()=>socket.close();state.socket=socket}catch(error){setTimeout(connectSocket,state.socketBackoff)}}