'use strict';
const $=s=>document.querySelector(s);
const D={canvas:$('#candleCanvas'),avatarCanvas:$('#avatarCanvas'),avatar:$('#avatar'),price:$('#currentPrice'),change24:$('#change24h'),volumeValue:$('#volume24hValue'),volumeChange:$('#volumeHourlyChange'),walletUsd:$('#carteiraUsdValue'),walletChange:$('#carteiraUsdChange'),pnlCard:$('#pnlCard'),pnlLabel:$('#pnlLabel'),pnlValue:$('#pnlValue'),pnlChange:$('#pnlChange'),priceMin:$('#priceMinValue'),priceMax:$('#priceMaxValue'),priceValue:$('#priceBarValue'),pricePtr:$('#priceBarPointer'),volMin:$('#volumeMinValue'),volMax:$('#volumeMaxValue'),volValue:$('#volumeBarValue'),volPtr:$('#volumeBarPointer'),rsiPtr:$('#rsiBarPointer'),rsiNum:$('#rsiBarValueNum'),rsiLabel:$('#rsiBarValueLabel'),marketDot:$('#marketDot'),marketStatus:$('#marketStatus'),lastUpdate:$('#lastUpdate'),modal:$('#carteiraModal'),inInteg:$('#inInteg'),inSol:$('#inSol'),inUsdc:$('#inUsdc'),inPreco:$('#inPrecoMedio'),save:$('#saveCarteiraBtn'),close:$('#closeCarteiraBtn'),note:$('#carteiraNote')};
const S={candles:[],ticker:null,price:0,prev:0,usdbrl:0,ws:null,lastDataAt:0,wallet:{integralizedBrl:0,sol:0,stable:0,avg:0}};
const API=['https://api.binance.com','https://data-api.binance.vision'];
const fmtUsd=v=>Number.isFinite(v)?'$ '+v.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2}):'$ --';
const fmtBrl=v=>Number.isFinite(v)?'R$ '+v.toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2}):'R$ --';
const fmtPct=v=>Number.isFinite(v)?`${v>=0?'▲':'▼'} ${Math.abs(v).toFixed(2).replace('.',',')}%`:'--';
const fmtVol=v=>{if(!Number.isFinite(v))return '--';if(v>=1e6)return (v/1e6).toFixed(2)+'M SOL';if(v>=1e3)return (v/1e3).toFixed(1)+'k SOL';return v.toFixed(1)+' SOL'};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const parseNum=v=>{const s=String(v??'').trim();if(!s)return 0;const n=Number(s.includes(',')?s.replace(/\./g,'').replace(',','.'):s);return Number.isFinite(n)?n:0};
async function fetchJson(path){let last;for(const base of API){try{const r=await fetch(base+path,{cache:'no-store'});if(!r.ok)throw new Error(String(r.status));return await r.json()}catch(e){last=e}}throw last||new Error('market unavailable')}
function loadWallet(){try{const v=JSON.parse(localStorage.getItem('sol_dashboard_wallet')||'{}');S.wallet={integralizedBrl:Number(v.integralizedBrl)||0,sol:Number(v.sol)||0,stable:Number(v.stable)||0,avg:Number(v.avg)||0}}catch(_){}}
function saveWallet(){localStorage.setItem('sol_dashboard_wallet',JSON.stringify(S.wallet))}
function ema(values,p){if(values.length<p)return null;let e=values.slice(0,p).reduce((a,b)=>a+b,0)/p,k=2/(p+1);for(let i=p;i<values.length;i++)e=values[i]*k+e*(1-k);return e}
function rsi(values,p=14){if(values.length<=p)return 50;let gain=0,loss=0;for(let i=values.length-p;i<values.length;i++){const d=values[i]-values[i-1];if(d>=0)gain+=d;else loss-=d}if(loss===0)return 100;const rs=(gain/p)/(loss/p);return 100-(100/(1+rs))}
function setTone(el,v){el?.classList.remove('up','dn','neutral');if(el)el.classList.add(!Number.isFinite(v)?'neutral':v>=0?'up':'dn')}
function calc(){const c=S.candles;if(!c.length)return null;const closes=c.map(x=>x.close),vols=c.map(x=>x.volume),last=c.at(-1),day=c.slice(-48),first=day[0]||c[0],low=Math.min(...day.map(x=>x.low)),high=Math.max(...day.map(x=>x.high)),change=first?.open>0?(last.close/first.open-1)*100:null,vol24=day.reduce((a,x)=>a+x.volume,0),volWindow=c.slice(-48),vmin=Math.min(...volWindow.map(x=>x.volume)),vmax=Math.max(...volWindow.map(x=>x.volume)),prevVol=c.at(-2)?.volume||0,volDelta=prevVol>0?(last.volume/prevVol-1)*100:null;return{last,low,high,change,vol24,vmin,vmax,volDelta,rsi:rsi(closes),ema9:ema(closes,9),ema21:ema(closes,21)}}
function updateMetrics(){const x=calc();if(!x)return;S.price=x.last.close;D.price.textContent=fmtUsd(S.price);D.change24.textContent=fmtPct(x.change);setTone(D.change24,x.change);D.volumeValue.textContent=fmtVol(x.vol24);D.volumeChange.textContent=fmtPct(x.volDelta);setTone(D.volumeChange,x.volDelta);D.priceMin.textContent=fmtUsd(x.low);D.priceMax.textContent=fmtUsd(x.high);D.priceValue.textContent=fmtUsd(S.price);D.pricePtr.style.left=`${clamp((S.price-x.low)/Math.max(x.high-x.low,1e-9)*100,0,100)}%`;D.volMin.textContent=fmtVol(x.vmin);D.volMax.textContent=fmtVol(x.vmax);D.volValue.textContent=fmtVol(x.last.volume);D.volPtr.style.left=`${clamp((x.last.volume-x.vmin)/Math.max(x.vmax-x.vmin,1e-9)*100,0,100)}%`;D.rsiNum.textContent=x.rsi.toFixed(1).replace('.',',');D.rsiPtr.style.left=`${clamp(x.rsi,0,100)}%`;D.rsiLabel.textContent=x.rsi<30?'Sobrevenda':x.rsi>70?'Sobrecompra':'Neutro';updateWallet();drawChart();drawAvatar();document.title=`${x.change>=0?'↑':'↓'} ${fmtUsd(S.price)} | RSI ${x.rsi.toFixed(0)}`;D.lastUpdate.textContent='Atualizado '+new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit',second:'2-digit'});D.marketDot.className='dot ok';D.marketStatus.textContent='Ao vivo'}
function updateWallet(){const w=S.wallet,usd=S.price*w.sol+w.stable,brl=S.usdbrl>0?usd*S.usdbrl:NaN,pnl=Number.isFinite(brl)?brl-w.integralizedBrl:NaN,pct=w.integralizedBrl>0&&Number.isFinite(pnl)?pnl/w.integralizedBrl*100:NaN;D.walletUsd.textContent=fmtUsd(usd);D.walletChange.textContent=Number.isFinite(brl)?fmtBrl(brl):'Carteira local';D.pnlLabel.textContent=Number.isFinite(pnl)&&pnl<0?'Prejuízo':'Lucro';D.pnlValue.textContent=Number.isFinite(pnl)?fmtBrl(Math.abs(pnl)):'R$ --';D.pnlChange.textContent=Number.isFinite(pct)?fmtPct(pct):'--';setTone(D.pnlChange,pct);if(w.avg>0&&w.sol>0){const solPct=(S.price/w.avg-1)*100;D.pnlCard.title=`Preço médio: ${fmtUsd(w.avg)} · SOL ${fmtPct(solPct)}`}}
function prepareCanvas(canvas){const dpr=Math.min(window.devicePixelRatio||1,2),rect=canvas.getBoundingClientRect(),w=Math.max(320,Math.round(rect.width)),h=Math.max(220,Math.round(rect.height));if(canvas.width!==Math.round(w*dpr)||canvas.height!==Math.round(h*dpr)){canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr)}const ctx=canvas.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);return{ctx,w,h}}
function drawChart(){if(S.candles.length<2)return;const {ctx,w,h}=prepareCanvas(D.canvas),c=S.candles.slice(-72),padL=8,padR=64,padT=16,padB=24,cw=w-padL-padR,ch=h-padT-padB,prices=c.flatMap(x=>[x.low,x.high]),rawLo=Math.min(...prices),rawHi=Math.max(...prices),margin=Math.max((rawHi-rawLo)*.06,rawLo*.001),lo=rawLo-margin,hi=rawHi+margin,range=Math.max(hi-lo,1e-9),slot=cw/c.length,xOf=i=>padL+i*slot+slot/2,yOf=v=>padT+(1-(v-lo)/range)*ch;ctx.font="10px 'Space Mono'";ctx.textBaseline='middle';for(let i=1;i<5;i++){const f=i/5,y=padT+ch*f,p=hi-range*f;ctx.strokeStyle='rgba(255,255,255,.055)';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(padL,y);ctx.lineTo(w-padR,y);ctx.stroke();ctx.fillStyle='#5c6478';ctx.fillText('$'+p.toFixed(2),w-padR+6,y)}const bodyW=Math.min(10,Math.max(3,slot*.72));for(let i=0;i<c.length;i++){const z=c[i],up=z.close>=z.open,col=up?'#10b981':'#f05252',x=xOf(i),yh=yOf(z.high),yl=yOf(z.low),yo=yOf(z.open),yc=yOf(z.close),top=Math.min(yo,yc),bh=Math.max(2,Math.abs(yc-yo));ctx.strokeStyle=up?'rgba(16,185,129,.82)':'rgba(240,82,82,.82)';ctx.lineWidth=1.25;ctx.beginPath();ctx.moveTo(x,yh);ctx.lineTo(x,yl);ctx.stroke();ctx.fillStyle=col;ctx.fillRect(x-bodyW/2,top,bodyW,bh)}const last=c.at(-1),yp=yOf(last.close);ctx.setLineDash([4,4]);ctx.strokeStyle='rgba(237,240,250,.38)';ctx.beginPath();ctx.moveTo(padL,yp);ctx.lineTo(w-padR,yp);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#edf0fa';ctx.fillText('$'+last.close.toFixed(2),w-padR+6,yp);const t0=new Date(c[0].openTime),t1=new Date(last.openTime);ctx.fillStyle='#5c6478';ctx.textBaseline='bottom';ctx.fillText(t0.toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'}),padL,h-4);ctx.textAlign='right';ctx.fillText(t1.toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'}),w-padR,h-4);ctx.textAlign='left'}
function drawAvatar(){const c=S.candles.slice(-3),canvas=D.avatarCanvas;if(!c.length)return;const ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);const lo=Math.min(...c.map(x=>x.low)),hi=Math.max(...c.map(x=>x.high)),r=Math.max(hi-lo,1e-9),y=v=>4+(1-(v-lo)/r)*(h-8),slot=(w-6)/c.length,bw=Math.max(4,slot*.55);c.forEach((z,i)=>{const up=z.close>=z.open,col=up?'#10b981':'#f05252',x=3+i*slot+slot/2,yo=y(z.open),yc=y(z.close);ctx.strokeStyle=col;ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(x,y(z.high));ctx.lineTo(x,y(z.low));ctx.stroke();ctx.fillStyle=col;ctx.fillRect(x-bw/2,Math.min(yo,yc),bw,Math.max(2,Math.abs(yc-yo)))})}
function mapKline(r){return{openTime:Number(r[0]),open:Number(r[1]),high:Number(r[2]),low:Number(r[3]),close:Number(r[4]),volume:Number(r[5])}}
async function loadMarket(){try{const [rows,ticker,fx]=await Promise.all([fetchJson('/api/v3/klines?symbol=SOLUSDT&interval=30m&limit=96'),fetchJson('/api/v3/ticker/24hr?symbol=SOLUSDT'),fetchJson('/api/v3/ticker/price?symbol=USDTBRL').catch(()=>null)]);S.candles=Array.isArray(rows)?rows.map(mapKline).filter(x=>Number.isFinite(x.close)):[];S.ticker=ticker;S.usdbrl=Number(fx?.price)||S.usdbrl;S.lastDataAt=Date.now();updateMetrics();connectWs()}catch(e){D.marketDot.className='dot err';D.marketStatus.textContent='Falha na fonte';setTimeout(loadMarket,8000)}}
function connectWs(){if(S.ws&&S.ws.readyState<=1)return;try{const ws=new WebSocket('wss://stream.binance.com:9443/ws/solusdt@kline_30m');ws.onmessage=e=>{try{const m=JSON.parse(e.data),k=m.k;if(!k)return;const z={openTime:Number(k.t),open:Number(k.o),high:Number(k.h),low:Number(k.l),close:Number(k.c),volume:Number(k.v)},last=S.candles.at(-1);if(last&&last.openTime===z.openTime)S.candles[S.candles.length-1]=z;else if(!last||z.openTime>last.openTime)S.candles.push(z);S.candles=S.candles.slice(-96);S.prev=S.price;S.lastDataAt=Date.now();updateMetrics()}catch(_){}};ws.onclose=()=>{S.ws=null;setTimeout(connectWs,3500)};ws.onerror=()=>ws.close();S.ws=ws}catch(_){setTimeout(connectWs,5000)}}
function openModal(){const w=S.wallet;D.inInteg.value=w.integralizedBrl?String(w.integralizedBrl).replace('.',','):'';D.inSol.value=w.sol?String(w.sol).replace('.',','):'';D.inUsdc.value=w.stable?String(w.stable).replace('.',','):'';D.inPreco.value=w.avg?String(w.avg).replace('.',','):'';D.note.textContent='';D.modal.classList.add('open');D.modal.setAttribute('aria-hidden','false')}
function closeModal(){D.modal.classList.remove('open');D.modal.setAttribute('aria-hidden','true')}
D.avatar.addEventListener('click',openModal);D.close.addEventListener('click',closeModal);D.modal.addEventListener('click',e=>{if(e.target===D.modal)closeModal()});D.save.addEventListener('click',()=>{S.wallet={integralizedBrl:Math.max(0,parseNum(D.inInteg.value)),sol:Math.max(0,parseNum(D.inSol.value)),stable:Math.max(0,parseNum(D.inUsdc.value)),avg:Math.max(0,parseNum(D.inPreco.value))};saveWallet();updateWallet();D.note.textContent='Salvo neste navegador.';setTimeout(closeModal,500)});window.addEventListener('resize',()=>{drawChart();drawAvatar()});
loadWallet();loadMarket();setInterval(()=>{if(Date.now()-S.lastDataAt>90000)loadMarket()},30000);
